-- Curated from Tim Lomas' academic Positive Lexicography, linked from
-- https://www.drtimlomas.com/lexicography/cm4mi. Chinese text is paraphrased.

INSERT INTO emotion_concept (name, language, meaning, description, source_url)
VALUES
    -- 1-20: longing, time, and bittersweet memory
    ('Ansias', '西班牙语', '夹杂焦虑与牵挂的渴望', '当你强烈思念某个人，也同时担忧对方或害怕失去时，这份向往会带着明显的不安。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fernweh', '德语', '对遥远未知之地的思乡般渴望', '不是想回家，而是被从未抵达的远方召唤，仿佛那里才有另一种可能的生活。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hiraeth', '威尔士语', '对故土或已消逝归属的怀念', '它既像乡愁，也包含对再也回不去的时间、地方和旧日自己的追寻。', 'https://hifisamurai.github.io/lexicography/'),
    ('Morriña', '加利西亚语', '对故乡的低沉思念与乡愁', '离开熟悉的土地后，那种持续、安静、略带忧伤的想家之情。', 'https://hifisamurai.github.io/lexicography/'),
    ('Natsukashii (懐かしい)', '日语', '旧事重现时温暖而微酸的怀念', '某个味道、声音或物件突然唤回珍贵往昔，让人高兴它曾存在，也知道它已经过去。', 'https://hifisamurai.github.io/lexicography/'),
    ('Saudade', '葡萄牙语', '对缺席之人事物的忧郁渴望', '思念里同时住着爱、缺席与不确定：你珍惜曾经拥有的一切，却不知道它是否还会回来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sehnsucht', '德语', '对遥远或未曾实现生活的深切向往', '现实之外似乎还有另一条人生道路不断召唤你，而那份渴望也因难以抵达而疼痛。', 'https://hifisamurai.github.io/lexicography/'),
    ('Toska (тоска)', '俄语', '没有单一对象的深沉忧郁与渴望', '它可以是对故乡、某个人或某段时间的思念，也可能只是心里无法明确说出的空缺。', 'https://hifisamurai.github.io/lexicography/'),
    ('Weltschmerz', '德语', '因世界不如理想而生的伤感', '个人理想与现实世界之间的落差令人疲惫，悲伤仿佛不是来自一件具体的事。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tizita (ትዝታ)', '阿姆哈拉语', '对逝去人事的苦甜回忆与思念', '记忆带回温柔的旧时光，也同时提醒你那个人、地方或阶段已经离开。', 'https://hifisamurai.github.io/lexicography/'),
    ('Vemod', '瑞典语', '面对美好结束时温柔而认命的忧伤', '回望童年或一段已经完成的经历，既感激它曾发生，也平静地为它不再回来而难过。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dor', '罗马尼亚语', '对人、地方或时间的强烈苦甜思念', '想念并不只是缺席感，而像一句持续留在心里的“我想要你回来”。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hrepenenje', '斯洛文尼亚语', '对尚未发生之事的怀旧般向往', '你仿佛已经在怀念一个还没到来的未来，对可能发生的人生提前产生乡愁。', 'https://hifisamurai.github.io/lexicography/'),
    ('Elvágyódás', '匈牙利语', '渴望离开当下处境去往别处', '身在这里，心却不断投向别的地方，想暂时逃开眼前的生活与自己。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hiányérzet', '匈牙利语', '感觉某种难以辨认的东西缺失了', '生活看似完整，心里却一直知道少了什么，只是还无法说出它的名字。', 'https://hifisamurai.github.io/lexicography/'),
    ('Utakata (泡沫)', '日语', '如泡沫般短暂易逝的感受', '美好事物刚刚出现便可能消散，因此眼前一刻显得轻盈、脆弱而值得凝视。', 'https://hifisamurai.github.io/lexicography/'),
    ('Charmolypi (χαρμολύπη)', '希腊语', '喜悦与哀伤同时存在的甜美忧愁', '告别、纪念或成长中的快乐并不排斥悲伤，两种感觉可以在同一刻彼此照亮。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bēi xǐ jiāo jí (悲喜交集)', '中文', '悲伤与喜悦交织在一起', '一件事同时带来获得与失去，让人既想笑又想哭，无法只用单一情绪概括。', 'https://hifisamurai.github.io/lexicography/'),
    ('Otožno', '斯洛文尼亚语', '柔软轻微的忧伤或惆怅', '它不是压倒性的痛苦，而是一层安静、温和、允许人停留片刻的悲伤。', 'https://hifisamurai.github.io/lexicography/'),
    ('Boghz (بغض)', '波斯语', '哭泣前堵在喉咙或胸口的情绪结', '难过尚未化成眼泪或话语，先在身体里累积成哽咽与紧绷。', 'https://hifisamurai.github.io/lexicography/'),

    -- 21-40: belonging, home, and community
    ('Heimat', '德语', '使人产生归属的家园', '它可以是故乡，也可以是语言、记忆和关系共同构成的“我属于这里”。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cynefin', '威尔士语', '人与其熟悉栖居之地的深层关系', '出生地、长期生活的环境和习惯共同塑造出一种“我本该在这里”的感觉。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ibasho (居場所)', '日语', '一个能归属、合适并做自己的地方', '真正的居所不只是地址，而是你无需伪装、能够安心存在的位置或群体。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cwtch', '威尔士语', '兼具拥抱、庇护与安全角落的温暖', '它既可指一个真切的拥抱，也可指让人被接纳和保护的小小空间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Geborgenheit', '德语', '被保护、被接住的安全感', '你知道自己不会被伤害或抛下，于是身体和心都能卸下防备。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hygge', '丹麦语/挪威语', '由地方、陪伴与温暖构成的舒适满足', '柔和灯光、熟悉的人和不赶时间的相处，共同形成一种安稳的日常幸福。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gezellig', '荷兰语', '与亲近之人共享的温暖愉快氛围', '空间本身或许普通，但因亲密、轻松的共同体验而显得格外宜人。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kos', '挪威语', '亲密、温暖而舒服的共处状态', '和喜欢的人依偎、聊天或共享安静时光，外界暂时被挡在小小生活之外。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mysa', '瑞典语', '主动进入舒适惬意状态', '把自己安顿在柔软、温暖或愉快的活动里，允许生活慢下来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Trygghet', '瑞典语', '由安全、信任与确定组成的安稳感', '当环境和关系都足够可靠时，人可以放松警惕，相信自己会被妥善对待。', 'https://hifisamurai.github.io/lexicography/'),
    ('Asabiyyah (عصبية)', '阿拉伯语', '群体团结与共同体精神', '人们因为亲缘、经历或共同目标凝聚在一起，并愿意彼此承担责任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bayanihan', '他加禄语', '为共同目标互相出力的社区团结', '邻里主动协作完成一件事，帮助不是交易，而是“我们一起扛”的自然选择。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dugnad', '挪威语', '社区成员自愿完成共同任务', '大家贡献时间和劳动来改善共同生活，过程中也重新确认彼此属于同一个群体。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gadugi', '切罗基语', '为了共同福祉而合作劳动', '个体把力量放进集体事务中，通过互助让整个社区过得更好。', 'https://hifisamurai.github.io/lexicography/'),
    ('Convivencia', '西班牙语', '共同生活中形成的理解、感受与目的', '它超越简单共处，强调不同的人在长期相处中建立可共享的生活意义。', 'https://hifisamurai.github.io/lexicography/'),
    ('Inuuqatigiittiarniq', '因纽特语', '尊重他人并共同维护健康和谐的社区', '良好生活来自邻里间的尊重、和平相处和对所有人的共同关照。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gemeinschaftsgefühl', '德语', '与共同体相连并关心社会的感觉', '个人感到自己是更大群体的一部分，也愿意对他人的处境保持兴趣和责任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ah-un (阿吽)', '日语', '亲近之人无需言语的默契', '关系足够熟悉时，一个眼神、停顿或微小动作就能让双方理解彼此。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eshra (عشرة)', '阿拉伯语', '长期相识与共同经历积累的联结和义务', '多年相处让关心不必反复声明，它沉淀成自然的亲近与对彼此的责任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Koinōnía (κοινωνία)', '希腊语', '共同参与所形成的交流、联结与亲密', '人们不只是待在一起，而是在分享、协作和共同生活中真正彼此连接。', 'https://hifisamurai.github.io/lexicography/'),

    -- 41-60: grief, impermanence, and acceptance
    ('Anitya (अनित्य)', '梵语', '一切事物都处于变化并终将消逝的无常', '意识到人、关系和处境不会永远保持原样，失去因此成为生命结构的一部分。', 'https://hifisamurai.github.io/lexicography/'),
    ('Han (한)', '韩语', '积压的悲伤、遗憾与等待转机的希望', '个人或群体长久承受的伤痛没有完全消散，却仍保留事情终会缓和的愿望。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kintsugi (金継ぎ)', '日语', '以金修补破损并让裂痕成为价值的一部分', '破碎不必被藏起来，修复后的痕迹可以证明经历，也让事物获得新的完整。', 'https://hifisamurai.github.io/lexicography/'),
    ('Memento mori', '拉丁语', '记住死亡与生命有限', '对终点的提醒并非只为恐惧，而是让人看清此刻、选择和关系为何珍贵。', 'https://hifisamurai.github.io/lexicography/'),
    ('Memento vivere', '拉丁语', '记得活着并真正生活', '在忧虑、惯性或对死亡的注视之外，提醒自己仍要参与眼前的生命。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mono no aware (物の哀れ)', '日语', '因体会万物短暂无常而生的温柔感伤', '正因为花会谢、相聚会结束，普通瞬间才显得更动人、更值得珍惜。', 'https://hifisamurai.github.io/lexicography/'),
    ('Qué será será', '西班牙语表达', '接受事情终将按其方式发生', '面对不能控制的结果，人选择放下反复抗拒，带着一点认命继续向前。', 'https://hifisamurai.github.io/lexicography/'),
    ('Duḥkha (दुःख)', '梵语/巴利语', '生命中普遍存在的不满足、苦与不安', '即使没有剧烈痛苦，变化、执着和落差也会带来难以彻底填满的不圆满感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shiv''ah (שבעה)', '希伯来语', '犹太传统中持续七天的正式哀悼期', '失去亲人后，哀伤被允许占据明确的时间与空间，也由共同体陪伴承接。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sirva vigad', '匈牙利语', '含着眼泪享受欢乐的苦甜状态', '庆祝与哭泣并不矛盾，人可以在同一场相聚里感到快乐，也为失去而心酸。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ukiyo (浮世)', '日语', '漂浮而短暂的人世及其转瞬之美', '生活无法固定，正因一切会流逝，人反而更专注地活在眼前的美好里。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wabi-sabi (侘寂)', '日语', '欣赏不完美、老去与无常之美', '磨损、残缺和岁月痕迹不必被修饰，它们让事物显出真实、安静的生命感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Weemoed', '荷兰语', '能够承受并走过怀旧悲伤的柔韧心境', '悲伤仍然存在，但人没有被它淹没，而是带着轻微忧郁继续生活。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shōganai (しょうがない)', '日语', '承认事情无可避免或无法改变', '不是否认难过，而是在确认无能为力之后停止消耗，把注意力还给下一步。', 'https://hifisamurai.github.io/lexicography/'),
    ('Manqué', '法语', '对未能成为或实现之可能的缺憾', '你怀念的不是失去过的现实，而是那个差一点发生、如今已经关闭的人生版本。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gaman (我慢)', '日语', '在困境中保持耐心、克制与承受力', '痛苦没有立即消失，但人选择稳住自己，在不轻易抱怨中等待艰难时刻过去。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tīng tiān yóu mìng (听天由命)', '中文', '对天意或命运安排的接受', '当个人努力已经走到边界，便停止强求结果，让事情依其条件发展。', 'https://hifisamurai.github.io/lexicography/'),
    ('Maraṇa smṛti (मरण स्मृति)', '梵语/巴利语', '对死亡与生命有限性的观照练习', '通过不逃避终点来重新衡量当下，把有限时间放回真正重要的人与事。', 'https://hifisamurai.github.io/lexicography/'),
    ('Amor fati', '拉丁语', '爱自己的命运并接纳发生的一切', '不仅勉强忍受经历，而是把顺境与挫折都视作构成此生、无法删去的一部分。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sayang', '马来语/印度尼西亚语/他加禄语', '同时可表达疼爱、惋惜与未实现愿望', '面对珍爱的人事物，它既能说出温柔，也能承载失去或错过时的一声可惜。', 'https://hifisamurai.github.io/lexicography/'),

    -- 61-80: joy, calm, and awe
    ('Ânanda (आनन्द)', '梵语', '持久、内在而不依赖条件的喜悦', '它不是短暂兴奋，而是一种更深层的满足与精神性的安乐。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ataraxia (ἀταραξία)', '希腊语', '清醒、稳固而不受扰动的宁静', '外界仍有变化，但内心不再被每一次波动拖走，保持平和与明晰。', 'https://hifisamurai.github.io/lexicography/'),
    ('Boketto (ぼけっと)', '日语', '不带思绪地望向远处发呆', '短暂放下任务、自我和目的，只让目光停在远方，脑海安静地留白。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eudaimonia (εὐδαιμονία)', '希腊语', '充分发挥潜能而形成的丰盛人生', '它不是一时开心，而是当行动、品格和生活方向相互一致时产生的深层圆满。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fàng xīn (放心)', '中文', '放下担忧后重新安定的轻松', '确认事情或某个人安全可靠后，悬着的心终于能落回原处。', 'https://hifisamurai.github.io/lexicography/'),
    ('Firgun (פירגון)', '希伯来语', '毫不嫉妒地为他人的成功真心高兴', '别人的好运不会削弱自己，你愿意公开赞赏，像收到礼物一样分享那份喜悦。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fjaka', '克罗地亚语', '身心松弛、什么也不必做的甜美慵懒', '紧绷结束后，人允许身体慢下来，不把休息变成另一项需要完成的任务。', 'https://hifisamurai.github.io/lexicography/'),
    ('Friluftsliv', '挪威语', '在户外生活并与自然保持联结', '走进空气、树林和开阔地，不只为了运动，也为了恢复人与自然相处的节奏。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gelassenheit', '德语', '放下控制后的从容与安宁', '不再紧抓必须如何的念头，把自己交还给事情本来的节奏。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gökotta', '瑞典语', '清晨早起去聆听第一声鸟鸣', '为了季节与自然中短暂的声音特意早起，让一天从安静的期待开始。', 'https://hifisamurai.github.io/lexicography/'),
    ('Harikoa', '毛利语', '强烈而充盈的快乐与欢欣', '喜悦从内心扩散到身体，表现为兴奋、雀跃、庆祝或难以隐藏的好心情。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hózhó', '纳瓦霍语', '和平、平衡、美与和谐共存的状态', '人与自身、他人及周围世界处在恰当关系中，生活因此显得完整而有秩序。', 'https://hifisamurai.github.io/lexicography/'),
    ('Komorebi (木漏れ日)', '日语', '阳光穿过树叶形成的斑驳光影', '一个细小的自然景象让人停下脚步，感到安静、清亮或短暂的惊喜。', 'https://hifisamurai.github.io/lexicography/'),
    ('Muditā (मुदिता)', '梵语/巴利语', '因他人的幸福而生的共喜', '不比较、不占有，只因为另一个人正在快乐或成长而自然地感到快乐。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shinrin-yoku (森林浴)', '日语', '沉浸森林环境以恢复身心', '慢慢走入林木、气味、光线和声音之中，让注意力从压力返回身体与自然。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yūgen (幽玄)', '日语', '面对幽深不可尽知之美的感受', '景象没有把意义全部说完，正是那片不可解释的余地带来敬畏和想象。', 'https://hifisamurai.github.io/lexicography/'),
    ('Iduni', '约鲁巴语', '强烈、完整而难以言说的喜悦', '快乐超过普通语言可以精确描述的程度，只能作为一种充满全身的状态被体验。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pyt', '丹麦语', '对小挫折说“算了，没关系”的释然', '事情不完美却也不值得继续困住自己，于是轻轻放过它，也放过自己。', 'https://hifisamurai.github.io/lexicography/'),
    ('Niksen', '荷兰语', '没有目标地什么也不做', '暂时停止追求产出，不安排意义，只允许自己闲着、游荡或放空。', 'https://hifisamurai.github.io/lexicography/'),
    ('Susegad', '孔卡尼语', '悠闲从容并尽情生活的态度', '它把不慌不忙视为一种生活方式，在简单日常中享受充足而松弛的时间。', 'https://hifisamurai.github.io/lexicography/'),

    -- 81-100: relationships, intimacy, and transitions
    ('A chuisle', '爱尔兰盖尔语', '把挚爱称作“我的脉搏”', '对方与自己亲近得像维持生命的心跳，这个称呼把爱表达成身体的一部分。', 'https://hifisamurai.github.io/lexicography/'),
    ('Agapé (ἀγάπη)', '希腊语', '无条件、无私且带有奉献意味的爱', '这份爱不以回报为前提，更关心对方的存在与福祉。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aroha', '毛利语', '融合爱、关怀、同情与共情的情感', '对一个人的在意不仅是喜欢，也包含理解其处境并愿意给予照顾。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cafuné', '葡萄牙语', '用手指温柔梳理爱人头发的动作', '无需说话，只用缓慢、熟悉的触碰传递亲密、安慰和疼爱。', 'https://hifisamurai.github.io/lexicography/'),
    ('Coup de foudre', '法语', '如闪电击中般突然强烈的一见钟情', '初次相遇就产生几乎无法抵挡的吸引，感情来得迅速而震动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Forelsket', '挪威语', '正在坠入爱河或沉浸恋爱的状态', '新生的爱意让日常带上轻盈兴奋的滤镜，注意力不断回到那个人身上。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ishq (عشق)', '阿拉伯语', '炽烈、真切且全身心投入的爱', '爱强到占据一个人的精神与生活，带着热情、投入和难以抽离的力量。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jeong (정)', '韩语', '长期相处形成的深厚依恋与联结', '它未必浪漫，却会在共同生活、照顾和反复相处中慢慢累积，难以轻易割断。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kilig', '他加禄语', '与心动对象互动时如蝴蝶振翅的雀跃', '一个眼神或一句话让身体发颤、胃里发轻，喜欢变成藏不住的兴奋。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mamihlapinatapai', '雅甘语', '两人都想行动却等待对方先开始的无言对视', '欲望和犹豫同时存在，彼此已经读懂，却谁也没有先把那一步说出口。', 'https://hifisamurai.github.io/lexicography/'),
    ('Philia (φιλία)', '希腊语', '建立在熟悉、共同兴趣或品格上的友爱', '它不是浪漫激情，而是朋友之间互相欣赏、信任并愿意同行的感情。', 'https://hifisamurai.github.io/lexicography/'),
    ('Retrouvailles', '法语', '久别后与珍爱之人重逢的喜悦', '时间和距离曾把彼此分开，再见面的瞬间既有重新发现，也有熟悉感归位。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yuán fèn (缘分)', '中文', '让人与人相遇并产生联结的机缘', '某段关系像被许多偶然共同推到眼前，人们因此感到相识并非完全随机。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sèvdāh', '塞尔维亚-克罗地亚语', '热烈爱情中欢乐与痛苦交织的强度', '爱越深，亲近的喜悦与难以实现、可能失去的疼痛就越可能同时出现。', 'https://hifisamurai.github.io/lexicography/'),
    ('Zweisamkeit', '德语', '两个人主动共享并隔开外界的亲密独处', '两人像住进只属于彼此的小世界，孤独没有消失，却变成共同选择的安静。', 'https://hifisamurai.github.io/lexicography/'),
    ('Anam cara', '爱尔兰盖尔语', '灵魂朋友般深刻而真挚的友谊', '有些朋友不仅陪伴生活，也看见更深的自己，让关系带上精神性的信任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Téng (疼)', '中文', '爱得深切并夹杂担心与心疼', '对亲近之人的爱让你为其脆弱或辛苦而疼，关怀与忧虑难以分开。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kama muta (काममूत)', '梵语衍生学术概念', '突然被爱与联结打动的温暖情绪', '重逢、善意或共同体时刻会让胸口发热、眼眶湿润，短暂地感到人与人非常靠近。', 'https://hifisamurai.github.io/lexicography/'),
    ('Divvientulība', '拉脱维亚语', '情侣二人共同享受的满足独处', '两个人安静相伴，不需要更多社交，独处感因为彼此在场而变得完整。', 'https://hifisamurai.github.io/lexicography/'),
    ('Datsuzoku (脱俗)', '日语', '摆脱惯例与日常束缚的自由感', '离开熟悉规则或生活轨道时，旧身份暂时松开，新的可能开始出现。', 'https://hifisamurai.github.io/lexicography/')
ON CONFLICT (name, language) DO UPDATE SET
    meaning = EXCLUDED.meaning,
    description = EXCLUDED.description,
    source_url = EXCLUDED.source_url;
