-- Curated from Tim Lomas' academic Positive Lexicography, linked from
-- https://www.drtimlomas.com/lexicography/cm4mi. Chinese text is paraphrased.

INSERT INTO emotion_concept (name, language, meaning, description, source_url)
VALUES
    -- 1-20: longing, time, and bittersweet memory
    ('Ansias', '西班牙语', '夹杂焦虑与牵挂的渴望', '当你强烈思念某个人，也同时担忧对方或害怕失去时，这份向往会带着明显的不安。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fernweh', '德语', '对遥远未知之地的思乡般渴望', '不是想回家，而是被从未抵达的远方召唤，仿佛那里才有另一种可能的生活。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hiraeth', '威尔士语', '对故土或已消逝归属的怀念', '它既像乡愁，也包含对再也回不去的时间、地方和旧日自己的追寻。', 'https://hifisamurai.github.io/lexicography/'),
    ('Morriña', '加利西亚语', '对故乡的低沉思念与乡愁', '离开熟悉的土地后，那种持续、安静、略带忧伤的想家之情。', 'https://hifisamurai.github.io/lexicography/'),
    ('Natsukashii (懐かしい)', '日语', '旧事重现时温暖而微酸的怀念', '某个味道、声音或物件突然唤回珍贵往昔，让人高兴它曾存在，也知道它已经过去。', 'https://hifisamurai.github.io/lexicography/'),
    ('Saudade', '葡萄牙语', '对缺席之人事物的忧郁渴望', '思念里同时住着爱、缺席与不确定：你珍惜曾经拥有的一切，却不知道它是否还会回来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sehnsucht', '德语', '对遥远或未曾实现生活的深切向往', '现实之外似乎还有另一条人生道路不断召唤你，而那份渴望也因难以抵达而疼痛。', 'https://hifisamurai.github.io/lexicography/'),
    ('Toska (тоска)', '俄语', '没有单一对象的深沉忧郁与渴望', '它可以是对故乡、某个人或某段时间的思念，也可能只是心里无法明确说出的空缺。', 'https://hifisamurai.github.io/lexicography/'),
    ('Weltschmerz', '德语', '因世界不如理想而生的伤感', '个人理想与现实世界之间的落差令人疲惫，悲伤仿佛不是来自一件具体的事。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tizita (ትዝታ)', '阿姆哈拉语', '对逝去人事的苦甜回忆与思念', '记忆带回温柔的旧时光，也同时提醒你那个人、地方或阶段已经离开。', 'https://hifisamurai.github.io/lexicography/'),
    ('Vemod', '瑞典语', '面对美好结束时温柔而认命的忧伤', '回望童年或一段已经完成的经历，既感激它曾发生，也平静地为它不再回来而难过。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dor', '罗马尼亚语', '对人、地方或时间的强烈苦甜思念', '想念并不只是缺席感，而像一句持续留在心里的“我想要你回来”。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hrepenenje', '斯洛文尼亚语', '对尚未发生之事的怀旧般向往', '你仿佛已经在怀念一个还没到来的未来，对可能发生的人生提前产生乡愁。', 'https://hifisamurai.github.io/lexicography/'),
    ('Elvágyódás', '匈牙利语', '渴望离开当下处境去往别处', '身在这里，心却不断投向别的地方，想暂时逃开眼前的生活与自己。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hiányérzet', '匈牙利语', '感觉某种难以辨认的东西缺失了', '生活看似完整，心里却一直知道少了什么，只是还无法说出它的名字。', 'https://hifisamurai.github.io/lexicography/'),
    ('Utakata (泡沫)', '日语', '如泡沫般短暂易逝的感受', '美好事物刚刚出现便可能消散，因此眼前一刻显得轻盈、脆弱而值得凝视。', 'https://hifisamurai.github.io/lexicography/'),
    ('Charmolypi (χαρμολύπη)', '希腊语', '喜悦与哀伤同时存在的甜美忧愁', '告别、纪念或成长中的快乐并不排斥悲伤，两种感觉可以在同一刻彼此照亮。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bēi xǐ jiāo jí (悲喜交集)', '中文', '悲伤与喜悦交织在一起', '一件事同时带来获得与失去，让人既想笑又想哭，无法只用单一情绪概括。', 'https://hifisamurai.github.io/lexicography/'),
    ('Otožno', '斯洛文尼亚语', '柔软轻微的忧伤或惆怅', '它不是压倒性的痛苦，而是一层安静、温和、允许人停留片刻的悲伤。', 'https://hifisamurai.github.io/lexicography/'),
    ('Boghz (بغض)', '波斯语', '哭泣前堵在喉咙或胸口的情绪结', '难过尚未化成眼泪或话语，先在身体里累积成哽咽与紧绷。', 'https://hifisamurai.github.io/lexicography/'),

    -- 21-40: belonging, home, and community
    ('Heimat', '德语', '使人产生归属的家园', '它可以是故乡，也可以是语言、记忆和关系共同构成的“我属于这里”。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cynefin', '威尔士语', '人与其熟悉栖居之地的深层关系', '出生地、长期生活的环境和习惯共同塑造出一种“我本该在这里”的感觉。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ibasho (居場所)', '日语', '一个能归属、合适并做自己的地方', '真正的居所不只是地址，而是你无需伪装、能够安心存在的位置或群体。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cwtch', '威尔士语', '兼具拥抱、庇护与安全角落的温暖', '它既可指一个真切的拥抱，也可指让人被接纳和保护的小小空间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Geborgenheit', '德语', '被保护、被接住的安全感', '你知道自己不会被伤害或抛下，于是身体和心都能卸下防备。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hygge', '丹麦语/挪威语', '由地方、陪伴与温暖构成的舒适满足', '柔和灯光、熟悉的人和不赶时间的相处，共同形成一种安稳的日常幸福。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gezellig', '荷兰语', '与亲近之人共享的温暖愉快氛围', '空间本身或许普通，但因亲密、轻松的共同体验而显得格外宜人。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kos', '挪威语', '亲密、温暖而舒服的共处状态', '和喜欢的人依偎、聊天或共享安静时光，外界暂时被挡在小小生活之外。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mysa', '瑞典语', '主动进入舒适惬意状态', '把自己安顿在柔软、温暖或愉快的活动里，允许生活慢下来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Trygghet', '瑞典语', '由安全、信任与确定组成的安稳感', '当环境和关系都足够可靠时，人可以放松警惕，相信自己会被妥善对待。', 'https://hifisamurai.github.io/lexicography/'),
    ('Asabiyyah (عصبية)', '阿拉伯语', '群体团结与共同体精神', '人们因为亲缘、经历或共同目标凝聚在一起，并愿意彼此承担责任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bayanihan', '他加禄语', '为共同目标互相出力的社区团结', '邻里主动协作完成一件事，帮助不是交易，而是“我们一起扛”的自然选择。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dugnad', '挪威语', '社区成员自愿完成共同任务', '大家贡献时间和劳动来改善共同生活，过程中也重新确认彼此属于同一个群体。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gadugi', '切罗基语', '为了共同福祉而合作劳动', '个体把力量放进集体事务中，通过互助让整个社区过得更好。', 'https://hifisamurai.github.io/lexicography/'),
    ('Convivencia', '西班牙语', '共同生活中形成的理解、感受与目的', '它超越简单共处，强调不同的人在长期相处中建立可共享的生活意义。', 'https://hifisamurai.github.io/lexicography/'),
    ('Inuuqatigiittiarniq', '因纽特语', '尊重他人并共同维护健康和谐的社区', '良好生活来自邻里间的尊重、和平相处和对所有人的共同关照。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gemeinschaftsgefühl', '德语', '与共同体相连并关心社会的感觉', '个人感到自己是更大群体的一部分，也愿意对他人的处境保持兴趣和责任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ah-un (阿吽)', '日语', '亲近之人无需言语的默契', '关系足够熟悉时，一个眼神、停顿或微小动作就能让双方理解彼此。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eshra (عشرة)', '阿拉伯语', '长期相识与共同经历积累的联结和义务', '多年相处让关心不必反复声明，它沉淀成自然的亲近与对彼此的责任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Koinōnía (κοινωνία)', '希腊语', '共同参与所形成的交流、联结与亲密', '人们不只是待在一起，而是在分享、协作和共同生活中真正彼此连接。', 'https://hifisamurai.github.io/lexicography/'),

    -- 41-60: grief, impermanence, and acceptance
    ('Anitya (अनित्य)', '梵语', '一切事物都处于变化并终将消逝的无常', '意识到人、关系和处境不会永远保持原样，失去因此成为生命结构的一部分。', 'https://hifisamurai.github.io/lexicography/'),
    ('Han (한)', '韩语', '积压的悲伤、遗憾与等待转机的希望', '个人或群体长久承受的伤痛没有完全消散，却仍保留事情终会缓和的愿望。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kintsugi (金継ぎ)', '日语', '以金修补破损并让裂痕成为价值的一部分', '破碎不必被藏起来，修复后的痕迹可以证明经历，也让事物获得新的完整。', 'https://hifisamurai.github.io/lexicography/'),
    ('Memento mori', '拉丁语', '记住死亡与生命有限', '对终点的提醒并非只为恐惧，而是让人看清此刻、选择和关系为何珍贵。', 'https://hifisamurai.github.io/lexicography/'),
    ('Memento vivere', '拉丁语', '记得活着并真正生活', '在忧虑、惯性或对死亡的注视之外，提醒自己仍要参与眼前的生命。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mono no aware (物の哀れ)', '日语', '因体会万物短暂无常而生的温柔感伤', '正因为花会谢、相聚会结束，普通瞬间才显得更动人、更值得珍惜。', 'https://hifisamurai.github.io/lexicography/'),
    ('Saṃsāra (संसार)', '梵语', '生命在变化与反复流转中的世间循环', '得到、失去和重新开始不断出现，个人体验到生活并非静止，而是持续流动的过程。', 'https://hifisamurai.github.io/lexicography/'),
    ('Duḥkha (दुःख)', '梵语/巴利语', '生命中普遍存在的不满足、苦与不安', '即使没有剧烈痛苦，变化、执着和落差也会带来难以彻底填满的不圆满感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shiv''ah (שבעה)', '希伯来语', '犹太传统中持续七天的正式哀悼期', '失去亲人后，哀伤被允许占据明确的时间与空间，也由共同体陪伴承接。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sirva vigad', '匈牙利语', '含着眼泪享受欢乐的苦甜状态', '庆祝与哭泣并不矛盾，人可以在同一场相聚里感到快乐，也为失去而心酸。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ukiyo (浮世)', '日语', '漂浮而短暂的人世及其转瞬之美', '生活无法固定，正因一切会流逝，人反而更专注地活在眼前的美好里。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wabi-sabi (侘寂)', '日语', '欣赏不完美、老去与无常之美', '磨损、残缺和岁月痕迹不必被修饰，它们让事物显出真实、安静的生命感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Weemoed', '荷兰语', '能够承受并走过怀旧悲伤的柔韧心境', '悲伤仍然存在，但人没有被它淹没，而是带着轻微忧郁继续生活。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shōganai (しょうがない)', '日语', '承认事情无可避免或无法改变', '不是否认难过，而是在确认无能为力之后停止消耗，把注意力还给下一步。', 'https://hifisamurai.github.io/lexicography/'),
    ('Manqué', '法语', '对未能成为或实现之可能的缺憾', '你怀念的不是失去过的现实，而是那个差一点发生、如今已经关闭的人生版本。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gaman (我慢)', '日语', '在困境中保持耐心、克制与承受力', '痛苦没有立即消失，但人选择稳住自己，在不轻易抱怨中等待艰难时刻过去。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tīng tiān yóu mìng (听天由命)', '中文', '对天意或命运安排的接受', '当个人努力已经走到边界，便停止强求结果，让事情依其条件发展。', 'https://hifisamurai.github.io/lexicography/'),
    ('Maraṇa smṛti (मरण स्मृति)', '梵语/巴利语', '对死亡与生命有限性的观照练习', '通过不逃避终点来重新衡量当下，把有限时间放回真正重要的人与事。', 'https://hifisamurai.github.io/lexicography/'),
    ('Amor fati', '拉丁语', '爱自己的命运并接纳发生的一切', '不仅勉强忍受经历，而是把顺境与挫折都视作构成此生、无法删去的一部分。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sayang', '马来语/印度尼西亚语/他加禄语', '同时可表达疼爱、惋惜与未实现愿望', '面对珍爱的人事物，它既能说出温柔，也能承载失去或错过时的一声可惜。', 'https://hifisamurai.github.io/lexicography/'),

    -- 61-80: joy, calm, and awe
    ('Ânanda (आनन्द)', '梵语', '持久、内在而不依赖条件的喜悦', '它不是短暂兴奋，而是一种更深层的满足与精神性的安乐。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ataraxia (ἀταραξία)', '希腊语', '清醒、稳固而不受扰动的宁静', '外界仍有变化，但内心不再被每一次波动拖走，保持平和与明晰。', 'https://hifisamurai.github.io/lexicography/'),
    ('Boketto (ぼけっと)', '日语', '不带思绪地望向远处发呆', '短暂放下任务、自我和目的，只让目光停在远方，脑海安静地留白。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eudaimonia (εὐδαιμονία)', '希腊语', '充分发挥潜能而形成的丰盛人生', '它不是一时开心，而是当行动、品格和生活方向相互一致时产生的深层圆满。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fàng xīn (放心)', '中文', '放下担忧后重新安定的轻松', '确认事情或某个人安全可靠后，悬着的心终于能落回原处。', 'https://hifisamurai.github.io/lexicography/'),
    ('Firgun (פירגון)', '希伯来语', '毫不嫉妒地为他人的成功真心高兴', '别人的好运不会削弱自己，你愿意公开赞赏，像收到礼物一样分享那份喜悦。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fjaka', '克罗地亚语', '身心松弛、什么也不必做的甜美慵懒', '紧绷结束后，人允许身体慢下来，不把休息变成另一项需要完成的任务。', 'https://hifisamurai.github.io/lexicography/'),
    ('Friluftsliv', '挪威语', '在户外生活并与自然保持联结', '走进空气、树林和开阔地，不只为了运动，也为了恢复人与自然相处的节奏。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gelassenheit', '德语', '放下控制后的从容与安宁', '不再紧抓必须如何的念头，把自己交还给事情本来的节奏。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gökotta', '瑞典语', '清晨早起去聆听第一声鸟鸣', '为了季节与自然中短暂的声音特意早起，让一天从安静的期待开始。', 'https://hifisamurai.github.io/lexicography/'),
    ('Harikoa', '毛利语', '强烈而充盈的快乐与欢欣', '喜悦从内心扩散到身体，表现为兴奋、雀跃、庆祝或难以隐藏的好心情。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hózhó', '纳瓦霍语', '和平、平衡、美与和谐共存的状态', '人与自身、他人及周围世界处在恰当关系中，生活因此显得完整而有秩序。', 'https://hifisamurai.github.io/lexicography/'),
    ('Komorebi (木漏れ日)', '日语', '阳光穿过树叶形成的斑驳光影', '一个细小的自然景象让人停下脚步，感到安静、清亮或短暂的惊喜。', 'https://hifisamurai.github.io/lexicography/'),
    ('Muditā (मुदिता)', '梵语/巴利语', '因他人的幸福而生的共喜', '不比较、不占有，只因为另一个人正在快乐或成长而自然地感到快乐。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shinrin-yoku (森林浴)', '日语', '沉浸森林环境以恢复身心', '慢慢走入林木、气味、光线和声音之中，让注意力从压力返回身体与自然。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yūgen (幽玄)', '日语', '面对幽深不可尽知之美的感受', '景象没有把意义全部说完，正是那片不可解释的余地带来敬畏和想象。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pohoda', '捷克语', '平和、幸福且一切顺遂的舒适状态', '环境与内心都没有明显阻力，人可以轻松地享受当下，觉得日子正好。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pyt', '丹麦语', '对小挫折说“算了，没关系”的释然', '事情不完美却也不值得继续困住自己，于是轻轻放过它，也放过自己。', 'https://hifisamurai.github.io/lexicography/'),
    ('Niksen', '荷兰语', '没有目标地什么也不做', '暂时停止追求产出，不安排意义，只允许自己闲着、游荡或放空。', 'https://hifisamurai.github.io/lexicography/'),
    ('Susegad', '孔卡尼语', '悠闲从容并尽情生活的态度', '它把不慌不忙视为一种生活方式，在简单日常中享受充足而松弛的时间。', 'https://hifisamurai.github.io/lexicography/'),

    -- 81-100: relationships, intimacy, and transitions
    ('A chuisle', '爱尔兰盖尔语', '把挚爱称作“我的脉搏”', '对方与自己亲近得像维持生命的心跳，这个称呼把爱表达成身体的一部分。', 'https://hifisamurai.github.io/lexicography/'),
    ('Agapé (ἀγάπη)', '希腊语', '无条件、无私且带有奉献意味的爱', '这份爱不以回报为前提，更关心对方的存在与福祉。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aroha', '毛利语', '融合爱、关怀、同情与共情的情感', '对一个人的在意不仅是喜欢，也包含理解其处境并愿意给予照顾。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cafuné', '葡萄牙语', '用手指温柔梳理爱人头发的动作', '无需说话，只用缓慢、熟悉的触碰传递亲密、安慰和疼爱。', 'https://hifisamurai.github.io/lexicography/'),
    ('Coup de foudre', '法语', '如闪电击中般突然强烈的一见钟情', '初次相遇就产生几乎无法抵挡的吸引，感情来得迅速而震动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Forelsket', '挪威语', '正在坠入爱河或沉浸恋爱的状态', '新生的爱意让日常带上轻盈兴奋的滤镜，注意力不断回到那个人身上。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ishq (عشق)', '阿拉伯语', '炽烈、真切且全身心投入的爱', '爱强到占据一个人的精神与生活，带着热情、投入和难以抽离的力量。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jeong (정)', '韩语', '长期相处形成的深厚依恋与联结', '它未必浪漫，却会在共同生活、照顾和反复相处中慢慢累积，难以轻易割断。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kilig', '他加禄语', '与心动对象互动时如蝴蝶振翅的雀跃', '一个眼神或一句话让身体发颤、胃里发轻，喜欢变成藏不住的兴奋。', 'https://hifisamurai.github.io/lexicography/'),
    ('Coup de cœur', '法语', '突然被某人或某物深深打动与吸引', '心像被瞬间击中，可能是心动、迷恋，也可能是对作品或地方产生强烈偏爱。', 'https://hifisamurai.github.io/lexicography/'),
    ('Philia (φιλία)', '希腊语', '建立在熟悉、共同兴趣或品格上的友爱', '它不是浪漫激情，而是朋友之间互相欣赏、信任并愿意同行的感情。', 'https://hifisamurai.github.io/lexicography/'),
    ('Retrouvailles', '法语', '久别后与珍爱之人重逢的喜悦', '时间和距离曾把彼此分开，再见面的瞬间既有重新发现，也有熟悉感归位。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yuán fèn (缘分)', '中文', '让人与人相遇并产生联结的机缘', '某段关系像被许多偶然共同推到眼前，人们因此感到相识并非完全随机。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sèvdāh', '塞尔维亚-克罗地亚语', '热烈爱情中欢乐与痛苦交织的强度', '爱越深，亲近的喜悦与难以实现、可能失去的疼痛就越可能同时出现。', 'https://hifisamurai.github.io/lexicography/'),
    ('Zweisamkeit', '德语', '两个人主动共享并隔开外界的亲密独处', '两人像住进只属于彼此的小世界，孤独没有消失，却变成共同选择的安静。', 'https://hifisamurai.github.io/lexicography/'),
    ('Anam cara', '爱尔兰盖尔语', '灵魂朋友般深刻而真挚的友谊', '有些朋友不仅陪伴生活，也看见更深的自己，让关系带上精神性的信任。', 'https://hifisamurai.github.io/lexicography/'),
    ('Téng (疼)', '中文', '爱得深切并夹杂担心与心疼', '对亲近之人的爱让你为其脆弱或辛苦而疼，关怀与忧虑难以分开。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kama muta (काममूत)', '梵语衍生学术概念', '突然被爱与联结打动的温暖情绪', '重逢、善意或共同体时刻会让胸口发热、眼眶湿润，短暂地感到人与人非常靠近。', 'https://hifisamurai.github.io/lexicography/'),
    ('Divvientulība', '拉脱维亚语', '情侣二人共同享受的满足独处', '两个人安静相伴，不需要更多社交，独处感因为彼此在场而变得完整。', 'https://hifisamurai.github.io/lexicography/'),
    ('Datsuzoku (脱俗)', '日语', '摆脱惯例与日常束缚的自由感', '离开熟悉规则或生活轨道时，旧身份暂时松开，新的可能开始出现。', 'https://hifisamurai.github.io/lexicography/')
ON CONFLICT (name, language) DO UPDATE SET
    meaning = EXCLUDED.meaning,
    description = EXCLUDED.description,
    source_url = EXCLUDED.source_url;
-- 101-500: additional entries verified against the same Positive Lexicography source
INSERT INTO emotion_concept (name, language, meaning, description, source_url)
VALUES
    -- aesthetics
    ('Mannvasanai', '泰米尔语', '雨后泥土的芬芳', '当你闻到雨水落在干燥土地上散发出的独特泥土气息时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gluggaveður', '冰岛语', '窗前宜人的天气', '当你享受窗外宜人景色，却不愿置身寒冷狂风之中时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shibumi (渋味)', '日语', '简约含蓄的静美', '当你感受到一种简单、微妙、不张扬且毫不费力的美时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sirimiri', '西班牙语', '持续数小时甚至数天的细雨', '当你身处持续数小时甚至数天的极轻微雨中时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wabi (侘)', '日语', '残缺、陈旧、无常之美', '当你欣赏不完美与陈旧，感受无常与缺陷中那种黑暗、荒凉且崇高的美感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Celaje', '西班牙语', '朦胧虚幻的影像', '当你看到模糊不清却仿佛真实存在的影像，如天空色彩时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Chiaroscuro', '意大利语', '光影明暗的对比', '当你欣赏艺术作品中光线与阴影形成的强烈对比时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Glas', '威尔士语', '蓝绿纯净之光', '当你感受到蓝色、绿色或白色所代表的纯净、闪耀与青春气息时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kanso (簡素)', '日语', '优雅简洁，无杂乱', '当你欣赏一种具有吸引力的无杂乱优雅简约时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mångata', '瑞典语', '月光洒在水面的光路', '当你看到月光在水面上投射出的闪烁光路，如同一条由月光铺成的道路时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Rasa (रस)', '梵语', '情感精华、艺术感染力', '当你感受到艺术作品的核心情感主题，或作为观众被唤起的情感体验时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sabi (寂)', '日语', '孤独、荒凉、陈旧之美', '当你感受到一种因岁月流逝而带来的孤独与荒凉，并在陈旧中体会到独特的美感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shizen (自然)', '日语', '自然不做作的状态', '当你感受自然流露、毫无矫饰与刻意的心境时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Oju-ona', '约鲁巴语', '艺术眼光与设计审美', '当你拥有敏锐的艺术眼光，对设计细节与美感有着独特的感知力时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Summetría (συμμετρία)', '希腊语', '部分与整体的和谐', '当你体会到各部分与整体之间协调一致的比例与对称美时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dhvani (ध्वनि)', '梵语', '声音、回声、含蓄之意', '当你通过声音或回声，感知到艺术作品中暗示或隐藏的深层含义时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Einfuehlung', '德语', '移情、共感、艺术感知', '当你将情感投射其中，近距离感受艺术品质或意义，产生类似共情的直接感知时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Koko (考古)', '日语', '风化之美、严峻崇高', '当你体会到经岁月风化后的美感，以及一种严峻而崇高的意境时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Oju-inu', '约鲁巴语', '内在之眼，创意洞察力', '当你运用创意感知、洞察力并理解视觉意象时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ewa ode', '约鲁巴语', '外在容貌之美', '当你关注或展现外表的吸引力与外在的美貌时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ewa inu', '约鲁巴语', '内在本质之美', '当你感知或展现内在的本质吸引力与心灵之美时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Leggiadria', '意大利语', '优雅、可爱、漂亮', '当你展现出优雅、可爱、漂亮或精致的特质时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Recherché', '法语', '稀有、异域、不寻常', '当你体验到稀有、异域或与众不同的事物，且这种特质未被大众所理解或欣赏时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bella figura', '意大利语', '美好形象、优雅得体', '当你展现出良好的印象、精致的外表，并体现出优雅、得体与风格时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pulchritudo', '拉丁语', '肉体之美与道德卓越', '当你同时感受到外在的形体之美与内在的道德卓越时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shěnměi píláo (审美疲劳)', '中文', '审美疲劳、欣赏力下降', '当你因接触过多美好事物而感到审美疲劳，不再能欣赏其美感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kitsch', '德语', '俗丽、浅薄但讨喜', '当你面对那些虽美丑参半、魅力浅薄或虚假，但仍被部分欣赏的物体或艺术时。', 'https://hifisamurai.github.io/lexicography/'),
    -- relationship with nature/place
    ('Querencia', '西班牙语', '带来力量的安全之地', '当你身处感到安全并能从中汲取力量的地方时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Smultronställe', '瑞典语', '静谧的独处之地', '当你前往一个宁静且精心培育的地方休憩放松时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tūrangawaewae', '毛利语', '扎根与连接之处', '当你感到被赋予力量、扎根并与某地紧密相连时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Salsabil (سلسبيل)', '阿拉伯语', '天堂清凉纯泉', '当你感受到那清澈、凉爽且纯净的水流，仿佛身处天堂中的喷泉或泉水时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Iwigara', '拉拉穆里语', '生命完全交融', '当你感受到所有生命，包括物理和精神层面的完全互联与整合时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aranyhíd', '匈牙利语', '水面上的金色桥影', '当日出或日落时，阳光在水面上反射出金光，宛如一座连接天地的桥梁。', 'https://hifisamurai.github.io/lexicography/'),
    ('Arkadíā (Ἀρκαδία)', '希腊语', '与自然和谐的理想乡', '你向往一片田园般的理想之地，在那里生活与自然保持和谐。', 'https://hifisamurai.github.io/lexicography/'),
    ('Chōros (χῶρος)', '希腊语', '充满情感的地方', '当你身处一个让你感到亲切与喜爱的特定场所时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Viriditas', '拉丁语', '自然的生机与活力', '当你感受到自然神圣治愈力量与蓬勃生命力时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Magosaha', '萨马语', '为生计持续寻海', '当你因生计不得不持续在海上搜寻食物，被一生的漂泊塑造出对流浪的渴望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kō (候)', '日语', '七十二候之一', '当你处于被划分为七十二个不同候的年份中的某个微季节时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Skogluft', '挪威语', '引入森林气息的生活哲学', '当你将自然引入家中，通过呼吸森林空气来恢复身心时，这种实践与理念。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yillal', '古古伊米蒂尔语', '创世者行进歌径', '当你沿着标记创世者行进路线的土地或天空之歌径行走时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sea Ania', '雅基语', '晨曦下的美好世界', '当你沉浸于心灵中美好与神奇的世界时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Koyaanisqatsi', '霍皮语', '失衡的生活状态', '当你感到生活失衡、功能失调并渴望改变时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bergdenken', '德语', '对山的思绪梦想', '当你正在思考或梦想着山脉，即所谓的山思时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Huya Ania', '雅基语', '滋养生命的荒野世界', '当你身处荒野区域，感受到大自然孕育生命、滋养灵魂的力量时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Scotch mist', '苏格兰语', '细密如雾小雨', '当你遇到细雨，雨滴极细几乎像雾，但你能分辨出它在落下而非浓云时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ultima Thule', '拉丁语', '地平线之外的遥远之地', '当你探索到已知世界之外，抵达遥远、未知或极限边缘的地方时。', 'https://hifisamurai.github.io/lexicography/'),
    -- understanding/perception
    ('Je ne sais quoi', '法语', '难以言喻的特质', '当你感受到一种难以言喻、不可定义的美好特质时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nachträglichkeit', '德语', '延宕作用；事后赋予意义', '当你事后对早期事件赋予意义时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Oikeiôsis (οἰκείωσις)', '希腊语', '归属与亲近感', '当你将某物感知为属于自己，产生熟悉化、亲和或依恋的情感时，这是心理过程。', 'https://hifisamurai.github.io/lexicography/'),
    ('Desengaño', '西班牙语', '幻灭之后的清醒觉悟', '曾经相信的幻象破灭后，你看穿欺骗，也获得了更清醒的认识。', 'https://hifisamurai.github.io/lexicography/'),
    ('Etterpåklokskap', '挪威语', '事后聪明或后见之明', '当你犯错后获得的教训或后见之明时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Qué será será', '西班牙语', '顺其自然或命中注定', '当你接受或顺从命运、认为该发生的总会发生时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sattva (सत्त्व)', '梵语', '善良、纯净、平衡与完整', '当你感受到内心纯净、平衡与完整，或处于善良状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shì (勢)', '中文', '势；力量、趋势与有利局面', '当你利用趋势创造有利局面并掌握主动权时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Layogenic', '他加禄语', '远看近看反差', '当你发现某人或某物远看美好近看却不然时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Goya (گویا)', '乌尔都语', '假设或暂且不论', '当你为了故事讲述而悬置怀疑、假设某事成立时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Luchtkasteel', '荷兰语', '空中楼阁；幻象或梦境', '当你面对虚幻的幻象或梦境时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sobytie (Событие)', '俄语', '事件；多种存在过程的汇聚', '当多种不同的存在过程汇聚创造出一个事件时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Zwischenraum', '德语', '间隙；事物间或内部的空空间', '当你身处事物之间或内部的开放空空间时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tachlit (תכלית)', '希伯来语', '事物的实际目的与本质', '当你关注事物的实际目的、本质或现实事实时。', 'https://hifisamurai.github.io/lexicography/'),
    -- communication/interaction
    ('Dadirri', '恩甘吉乌米尔语', '充满灵性尊重的深度倾听', '当你进行深度反思与尊重的倾听时。', 'https://hifisamurai.github.io/lexicography/'),
    ('L’esprit de l’escalier', '法语', '事后想到的机智回应', '当你离开对话现场后，才突然想到当时该说的机智或犀利回答时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mokita', '基维拉语', '众所周知却无人提及的真相', '当你面对一个所有人都知道却无人谈论的真相时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nunchi (눈치)', '韩语', '察言观色的敏锐力', '当你敏锐感知情绪与情境并巧妙回应时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Treppenwitz', '德语', '事后想到的机智回应', '当你离开对话现场后，才突然想到当时该说的机智或犀利回答时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jiā yóu (加油)', '中文', '鼓励与坚持前行', '当你想要鼓励他人继续努力、坚持到底时，发出的加油打气的话语。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hoʻoponopono', '夏威夷语', '相互宽恕与补偿的互动', '当你进行相互宽恕与补偿的互动时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Taarradhin (تراض)', '阿拉伯语', '皆大欢喜的共识与和解', '当你达成让所有人受益的积极协议或妥协时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tsavd danem (Ցավդ տանեմ)', '亚美尼亚语', '愿为你分担痛苦的关怀', '当你表达愿为你分担痛苦时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aon (อ้อน)', '泰语', '撒娇以博取情感回应', '当你通过情感诉求或哭泣来博取对方喜爱时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ghahr Kardan (قهر کردن)', '波斯语', '因生气而停止交流', '当你因生气或不满而停止与某人交流时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nja', '瑞典语', '既非肯定也非否定的犹豫', '当你表达不确定或同时包含肯定与否定时。', 'https://hifisamurai.github.io/lexicography/'),
    ('S’entendre', '法语', '彼此理解与相处融洽', '当你彼此理解、意见一致或相处融洽时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Xīn kǔ (辛苦)', '中文', '对他人的体谅与感激', '当你体谅他人辛劳并表达感激与认可时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yilugnta (ይሉኝታ)', '阿姆哈拉语', '尊重并顾及他人意见', '当你感到有义务尊重并顾及他人意见时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Báo ơn', '越南语', '回报恩惠与感谢', '当你收到帮助时，通过行动或言语回报、感谢并表达尊重。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ngali', '吉瓦利语', '包括你在内的我们俩', '当你指代包括听话者在内的两个人时，使用这个特定的复数代词。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ngaliju', '吉瓦利语', '不包括你的我们俩', '当你指代不包括听话者在内的两个人时，使用这个特定的复数代词。', 'https://hifisamurai.github.io/lexicography/'),
    ('Enraonar', '加泰罗尼亚语', '文明理性的讨论方式', '当你以文明且理性的方式进行讨论时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Estağfurullah', '土耳其语', '谦虚回应赞美的客套', '当你回应赞美并表示不必提及或感谢时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mokusatsu (黙殺)', '日语', '以沉默拒绝或无视对方', '当你通过保持沉默来拒绝谈判报价时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Poldermodel', '荷兰语', '基于共识的对话解决问题', '当你通过对话解决难题时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Salām (سلام)', '阿拉伯语', '和平和谐与安宁的祝福', '当你传递和平、和谐、繁荣与安宁的问候时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shalom (שָׁלוֹם)', '希伯来语', '和平和谐与安宁的祝福', '当你传递和平、和谐、繁荣与安宁的问候时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sprachgefühl', '德语', '对语言恰当的直觉感知', '当你凭直觉感知语言是否得体及语言特质时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Stushevatsya (стушеваться)', '俄语', '悄然退场或消失', '当你安静地离开、从视野中淡出或变得不再重要时，所呈现的状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Talanoa', '斐济印地语', '作为社交粘合剂的闲聊', '当你通过讲故事或闲聊来维系社会关系时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wafwako', '基卢巴语', '真诚且语境的感谢', '当你根据具体语境，向对方表达强烈且真诚的感激之情时使用的短语。', 'https://hifisamurai.github.io/lexicography/'),
    ('Touché', '法语', '承认对方观点击中要害', '当你承认对方在争论中提出了有力的观点时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Glasnost (гла́сность)', '俄语', '公开透明的讨论过程', '当你参与公开讨论、建立关系或治理时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Milczeć', '波兰语', '保持沉默不语的状态', '当你选择保持安静、不发表言论时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Plámás', '盖尔语', '可能空洞虚伪的奉承', '当你使用甜言蜜语进行奉承时，这可能暗示着空洞或虚伪。', 'https://hifisamurai.github.io/lexicography/'),
    ('Stammtisch', '德语', '熟人间的定期友好聚会', '当你定期参加熟人间的非正式友好聚会时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pala', '他加禄语', '惊讶与出乎意料', '当你遇到与预期完全相反的情况时，发出的表示惊讶的感叹。', 'https://hifisamurai.github.io/lexicography/'),
    ('Schmooze', '意第绪语', '旨在获益的友好闲聊', '当你友好且具说服力地聊天以获取好感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wassail', '古英语', '祝愿对方安好健康', '当你向他人致以问候，祝愿其身体康健、一切安好时使用。', 'https://hifisamurai.github.io/lexicography/'),
    -- savoring/appreciation
    ('Petrichor', '英语', '雨后泥土的芬芳', '当你闻到雨水落在干燥土壤上产生的泥土气息时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Flâner', '法语', '悠闲地漫步街头', '当你悠闲地漫步街头，或作为观察者体验城市时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ohanami (お花見)', '日语', '聚集欣赏花卉的文化活动', '当你聚集在一起欣赏花卉（特别是樱花）时，它指代这种受文化重视的活动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Otsukaresama (お疲れ様)', '日语', '感谢辛勤工作的致意语', '当你表达感谢和欣赏时，它意为“谢谢你的辛勤工作”。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pau hana', '夏威夷语', '工作后珍贵的闲暇时光', '当你享受工作结束后用于社交或放松的宝贵时间时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Erfolgserlebnis', '德语', '成功落定时的成就感', '完成艰难任务或得到肯定时，成功带来的满足真实地落在心里。', 'https://hifisamurai.github.io/lexicography/'),
    ('Habseligkeiten', '德语', '最珍贵的私人物品', '当你拥有少量物品时，它指代你最珍贵、珍爱的财产。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mahalo', '夏威夷语', '感激、赞赏与尊重', '你真诚感谢、赞赏或尊重另一个人，并愿意把这份心意说出来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Njuta', '瑞典语', '深深享受或深刻欣赏', '当你深深享受或深刻欣赏某事时，它描述这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Passeggiata', '意大利语', '没有目的的悠闲漫步', '你没有赶路的目的，只是在街道上从容散步，让身体和注意力慢下来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Trouvaille', '法语', '偶然发现珍贵事物的幸运', '偶然遇见一件美好而有价值的事，意外发现本身就像收到礼物。', 'https://hifisamurai.github.io/lexicography/'),
    ('Uitwaaien', '荷兰语', '到风里散去杂乱思绪', '你走到风里或自然中，让空气吹散杂乱思绪，头脑渐渐恢复清明。', 'https://hifisamurai.github.io/lexicography/'),
    ('Volta (βόλτα)', '希腊语', '街头悠闲漫步的惬意', '你没有特定目的，只是沿着街道悠闲散步，享受城市与当下。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jedna báseň', '捷克语', '像诗一样美好的赞叹', '某件东西好得像一首诗，你忍不住赞叹它的品质与带来的愉悦。', 'https://hifisamurai.github.io/lexicography/'),
    ('Augenweide', '德语', '赏心悦目的美丽场景', '当你看到美丽、刺激或丰富的场景时，它指代这种视觉盛宴。', 'https://hifisamurai.github.io/lexicography/'),
    ('Blueschtfaehrtli', '德语', '驾车欣赏春花的闲游', '你在春天悠闲驾车出行，只为沿途欣赏刚刚盛开的花朵。', 'https://hifisamurai.github.io/lexicography/'),
    ('Enkelt', '丹麦语', '简单之中显现的美', '事物没有多余装饰，正是那份简洁让你看见安静而清楚的美。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aficionado', '西班牙语', '对某个领域热爱且熟稔的人', '你对一件事既有深厚兴趣，也积累了足够知识，愿意长期投入其中。', 'https://hifisamurai.github.io/lexicography/'),
    ('Estrenar', '西班牙语', '首次使用或穿戴某物', '当你第一次使用或穿戴某物时，它可能赋予穿戴者一种自信感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hugfanginn', '冰岛语', '心神被某人或某物吸引', '某个人或事物牢牢抓住你的注意力，让你着迷并久久不能移开。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nutaan atam', '尤皮克语', '确认此刻一切正好的满足', '事情终于准备妥当或圆满完成，你由衷觉得现在这样就很好。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sabsung', '泰语', '因生活增添趣味而恢复活力', '一件为生活增添乐趣的事让你重新振作，精神和兴致都回来了。', 'https://hifisamurai.github.io/lexicography/'),
    ('Entrückt', '德语', '沉浸其中而暂时忘我', '你被某件事深深吸引，沉浸在自己的世界里，暂时忘记周围。', 'https://hifisamurai.github.io/lexicography/'),
    ('Zevlovat', '捷克语', '好奇地闲逛或游荡', '当你好奇地凝视、闲逛或逗留时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Disfrutar', '西班牙语', '享受或受益于某事', '当你从某事中受益或享受时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Maadoittuminen', '芬兰语', '扎根自然的接地感', '当你通过扎根自然来确立自身存在时。', 'https://hifisamurai.github.io/lexicography/'),
    -- existence
    ('Angst', '丹麦语', '焦虑恐惧与阴郁', '当你感到焦虑、恐惧和阴郁时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dasein', '德语', '在此存在的在世状态', '当你意识到自己始终处于特定情境和情绪中，作为人存在于世间的状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Byt (быт)', '俄语', '琐碎的日常与私生活', '当你处于日常生活的琐碎、物质文化与私生活中时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eucatastrophe', '英语', '突然的幸运转折', '当你经历困境后迎来意想不到的美好结局，感受到命运眷顾的瞬间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Reiwa (令和)', '日语', '美丽吉祥的和谐和平', '当你感受到美丽、吉祥且有序的和谐与和平时。', 'https://hifisamurai.github.io/lexicography/'),
    -- love
    ('Jeong/jung (정)', '韩语', '深厚的情感与联结', '当你与某人建立深厚情感、亲和力或联结时，无论是否涉及浪漫关系。', 'https://hifisamurai.github.io/lexicography/'),
    ('Putuwa', '加达加尔语', '火边暖手与紧握', '当你围坐在火堆旁，一边温暖双手，一边轻柔地握住另一个人的手时，这种亲密与温情便油然而生。', 'https://hifisamurai.github.io/lexicography/'),
    ('Koi no yokan (恋の予感)', '日语', '预感会坠入爱河', '当你遇见某人，预感自己必将爱上对方的那种强烈直觉与情感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aloha', '夏威夷语', '充满爱的问候与告别', '当你用充满爱与慈悲的方式打招呼或告别，感受存在的呼吸。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bashert', '意第绪语', '命中注定；指天定的灵魂伴侣', '当你认定某人是命中注定的灵魂伴侣时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Te quiero', '西班牙语', '介于喜欢与爱之间的温柔', '当你表达介于喜欢与爱之间的温柔情感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Xiào (孝)', '中文', '孝顺与家族敬重', '当你以敬重之心对待长辈，履行对家族的责任与义务时，这种代际间的爱与尊重便得以体现。', 'https://hifisamurai.github.io/lexicography/'),
    ('Janid mernem (ջանիդ մեռնեմ)', '亚美尼亚语', '深切地爱或关怀', '当你深切地爱或强烈关怀某人时。', 'https://hifisamurai.github.io/lexicography/'),
    ('S''apprivoiser', '法语', '相互驯服与接纳', '当你与伴侣在关系中互相学习信任与接纳，建立深层联结的过程。', 'https://hifisamurai.github.io/lexicography/'),
    ('Abhisar (অভিসার)', '孟加拉语', '恋人间的秘密相会', '当你与恋人或伴侣进行秘密相会时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Onsra', '博罗语', '最后一次去爱；觉得爱不会长久', '当你怀着爱不会长久的预感，最后一次去爱某人时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Storge (στοργή', '希腊语', '家庭成员间的亲情', '当你感受到对家庭成员的关怀与情感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tabanca', '克里奥尔语', '相思病；被爱人离开后的痛苦', '当你被深爱的人离开，陷入相思之苦时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Voler bene', '意大利语', '深爱或非常喜爱', '当你以深情的方式爱或关怀某人时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Apaixonar', '葡萄牙语', '坠入爱河；对某人或某事充满激情', '当你坠入爱河，或开始对某人某事充满激情时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Naz (ناز)', '乌尔都语', '因被无条件爱而产生的骄傲与自信', '当你因感受到无条件的爱，而流露出骄傲与自信时。', 'https://hifisamurai.github.io/lexicography/'),
    ('кохати', '乌克兰语', '充满激情的亲密之爱', '当你以充满激情、亲密或浪漫的方式去爱一个人时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Odnolyub (однолюб)', '俄语', '一生只爱一人；专一者或单配偶主义者', '当你一生只爱或曾只爱一个女人，成为专一者时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ludus', '拉丁语', '带着游戏心态的爱情', '两个人把爱情当作轻松的游戏，其中有调情、玩心与享受当下。', 'https://hifisamurai.github.io/lexicography/'),
    ('Prâgma (πρᾶγμα)', '希腊语', '行为；指理性或明智的爱', '当你以理性或明智的方式去爱，将其视为一种行为时。', 'https://hifisamurai.github.io/lexicography/'),
    -- communality
    ('Zastólʹje (застолье)', '俄语', '与友共饮的盛宴', '当你与朋友们围坐在桌旁，一边吃喝一边畅聊，享受这场欢乐的聚餐时，这种团聚的喜悦便洋溢。', 'https://hifisamurai.github.io/lexicography/'),
    ('Agora (Αγορά)', '希腊语', '公共集会广场', '当你身处用于市场、辩论或大众聚会的公共空间时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mitsein', '德语', '与他人同在', '当你体验到人类在存在论上始终已与他人共在的状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Salon', '法语', '文学艺术沙龙', '当你身处由女性主持的文学艺术聚会，在客厅般的空间里交流思想与作品时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Simpatía', '西班牙语', '关系中的和谐一致', '当你感受到人际关系或社会群体中那种融洽、和谐且一致的氛围时，这种亲切感便自然流露。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sobornost (Собо́рность)', '俄语', '基于爱的精神统一', '当你体验到一种基于集体之爱的精神和谐，灵魂在宗教共同体中凝聚并达成统一时，这种神圣感便降临。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tjotjog', '爪哇语', '关系中的和谐一致', '当你处于一种彼此契合、关系融洽且社会氛围和谐的状态中时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tuko pamoja', '斯瓦希里语', '在一起的地方与团结', '当你感受到“我们在一起”的社区团结感，身处同一个地方并彼此连接时，这种归属感便强烈。', 'https://hifisamurai.github.io/lexicography/'),
    ('Motirõ', '图皮瓜拉尼语', '社区共建劳动', '当你与人们聚集在一起，共同劳作或建造有益事物时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bonhomie', '法语', '愉快的友好与亲切', '当你展现出友善、亲切、和蔼且热诚的态度时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Folkelig', '丹麦语', '大众化的民主精神', '当你感受到一种属于大众、具有广泛吸引力且体现民主民族精神的情感时，这种亲切感便深入人心。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mishloach manot (משלוח מנות )', '希伯来语', '互赠食物礼盒', '当你通过交换食物和饮料的礼物，践行互赠份额的传统时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tegsh', '蒙古语', '与世界的平衡', '当你处于与社区及更广阔世界保持平衡的受推崇状态时。', 'https://hifisamurai.github.io/lexicography/'),
    -- soul
    ('Qì (氣)', '中文', '生命能量或气息', '当你感到体内流动着一种维持生命活力的能量，如同呼吸般自然且充满生机时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ātman/attā (आत्मन्).', '巴利语', '生命内在的自我与精神本质', '你试图理解生命内部那个与呼吸、精神和自我相连的核心。', 'https://hifisamurai.github.io/lexicography/'),
    ('Enthousiasmos (ἐνθουσιασμός)', '希腊语', '神性灵感状态', '当你被神灵或力量启发、附体，或受更高力量指引驱动时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fitra (فطرة)', '阿拉伯语', '天性纯真本能', '当你描述一种与神亲近的纯真天性和本能倾向时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ib', '埃及语', '身心情感之心', '当你将心脏视为情感、思想、意志和意图的所在时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ondinnonk', '易洛魁语', '灵魂隐秘愿望', '当你通过梦境揭示灵魂最秘密、最内在的欲望或愿望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tat Tvam Asi (तत्त्वमसि)', '梵语', '你就是那本质', '当你表达阿特曼与梵是一体的核心哲学时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Vozdukh (Воздух)', '俄语', '呼吸灵魂气息', '当你通过吸气将灵魂吸入体内，呼气将灵魂呼出体外时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hiimor (Хийморь)', '蒙古语', '风马，承载祈愿的灵魂能量', '当你感到内心充满力量，仿佛能如风般迅速、如马般有力地传递信念与希望时，这种精神能量便如风马般存在。', 'https://hifisamurai.github.io/lexicography/'),
    ('Anima', '拉丁语', '灵魂、精神、呼吸与心智', '你想表达一个人内在的生命力、精神本质或心智活动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Seelisch', '德语', '属于灵魂、精神或心理的体验', '你想描述一种关乎内在本质、精神状态或心理活动的感受。', 'https://hifisamurai.github.io/lexicography/'),
    -- spirit/effort
    ('Kefi (κέφι)', '希腊语', '快乐、激情或高昂的精神', '当你沉浸在极度的快乐、激情或狂热的情绪中，感到精神高度亢奋时，这种状态正是凯菲的体现。', 'https://hifisamurai.github.io/lexicography/'),
    ('Brio', '意大利语', '活力、热情与自信', '你带着充沛活力、热情和自信投入生活或创作，整个人精神昂扬。', 'https://hifisamurai.github.io/lexicography/'),
    ('Overskud', '丹麦语', '超出日常所需的余力', '完成必要事务后，你仍有多余精力和资源，可以从容帮助别人或应对变化。', 'https://hifisamurai.github.io/lexicography/'),
    ('Startijenn', '布列塔尼语', '开始行动并坚持下去的能量', '一股初始动力推动你开始行动，随后又转化为把事情坚持到底的韧性。', 'https://hifisamurai.github.io/lexicography/'),
    ('Thumos/thymos (θυμός)', '希腊语', '血气、精神或对认可的渴望', '当你感到一种基于血气方刚的精神力量，并渴望获得他人认可时，这种充满生命力的情感便是图莫斯。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tubli', '爱沙尼亚语', '勤奋、可靠而坚韧的品格', '你认真做事，在困难中仍保持勤奋、可靠和有力量的状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Curglaff', '苏格兰语', '突然进入冷水时的振奋感', '当你突然跳入冷水中，感到一阵刺激、清醒且充满活力的瞬间体验时，这种振奋感便是库尔格拉夫。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eigenwillig', '德语', '按照自身意志坚持个性', '你依照自己的性格和方式行事，不因外界压力轻易放弃个人意志。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sterkte', '荷兰语', '祝愿他人拥有力量与好运', '面对他人的努力或难关，你祝愿对方获得足够力量，也拥有好运。', 'https://hifisamurai.github.io/lexicography/'),
    ('Volya (воля)', '俄语', '意志、力量或自由', '当你感受到强烈的意志力、内在力量或追求自由的快乐时，这种精神力量便是沃利亚。', 'https://hifisamurai.github.io/lexicography/'),
    ('Baraka (بركة)', '阿拉伯语', '带有祝福意味的精神力量', '你感到一股带有祝福意味的精神力量，仿佛行动因此获得支撑。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jaksaa', '芬兰语', '拥有完成任务的能量与精神', '当你感到自己充满精力、力量和斗志，准备好迎接某项任务时，这种状态便是雅克萨。', 'https://hifisamurai.github.io/lexicography/'),
    ('Khalas (خلاص)', '阿拉伯语', '事情彻底结束后的解脱', '一件事终于完成并不可逆转，你在终结感中同时体会到释然。', 'https://hifisamurai.github.io/lexicography/'),
    ('Orka', '瑞典语', '有精力把事情做下去', '你感到自己还有足够能量、韧性和兴致，可以继续完成眼前的事。', 'https://hifisamurai.github.io/lexicography/'),
    -- transformation
    ('Kenshō (見性)', '日语', '见性觉悟', '当你瞥见自己的本性或本质，经历初次或短暂的觉醒时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Satori (悟り)', '日语', '顿悟', '当你获得理解、领悟或经历觉醒与觉悟的时刻。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fanaa (فناء)', '阿拉伯语', '自我消亡', '当你经历自我的毁灭与克服，从而获得觉悟并与神合一的瞬间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mokṣa/moksha (मोक्ष)', '巴利语', '解脱', '当你获得解放、自由或从轮回中释放的瞬间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bhagavad/t (भगवद्)', '梵语', '受祝福者', '当你被巨大的功德所滋养，成为受祝福的人，或作为亲昵的称呼时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kalyāṇa-mitratā/mittatā (कल्याण मित्रता)', '梵语', '促进彼此成长的精神友谊', '一段友谊建立在善意与精神共鸣上，双方陪伴并帮助彼此成长。', 'https://hifisamurai.github.io/lexicography/'),
    ('Agon (ἀγών)', '希腊语', '在竞争与冲突中争取成长', '你进入一场对抗或竞争，在投入和冲突中推动事情发生转变。', 'https://hifisamurai.github.io/lexicography/'),
    ('Vipāka (विपाक)', '巴利语', '业力成熟', '当你见证业力的结果、成熟或最终显现的时刻。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ta''ala (تعالى)', '阿拉伯语', '超越与崇高', '当你超越凡俗，拥有神圣优越性，或感到被高高在上地轻视时。', 'https://hifisamurai.github.io/lexicography/'),
    -- flourishing
    ('Ikigai (生き甲斐)', '日语', '生存意义', '当你找到生活的理由、价值或目标时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sternstunde', '德语', '重大且短暂的关键时刻', '当你经历罕见且意义重大的时刻，事件虽短暂却影响深远时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Carpe Diem', '拉丁语', '把握当下', '当你充分利用当下时刻或机会时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Genki (元気)', '日语', '充满活力与健康的精神状态', '当你感到精力充沛、身心健康，洋溢着蓬勃的生命力与朝气时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Joie de vivre', '法语', '生活之乐', '当你感受到对生活的喜悦、活力与热情，懂得如何生活时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sóphrosuné (σωφροσύνη)', '希腊语', '品格卓越与心智健全的状态', '当你展现出节制、自律与心智健全，拥有卓越品格时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bon vivant', '法语', '享受并欣赏美好生活的人', '当你沉浸在美食、美酒与舒适生活中，感受到对美好事物的敏锐感知与享受时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Euphoría (εὐφορία)', '希腊语', '极度愉悦', '当你感到极度兴奋或快乐时。', 'https://hifisamurai.github.io/lexicography/'),
    ('La’asot chaim (לעשות חיים)', '希伯来语', '尽情生活', '当你创造生活、充分享受生活或玩得开心时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Livsnjutare', '瑞典语', '生活享乐者', '当你热爱生命并充分享受生活时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jìn qû (进取)', '中文', '积极进取', '当你主动、有抱负、不断进步或勇往直前时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pura vida', '西班牙语', '纯粹生活', '当你秉持纯粹或简单的生活哲学与方式时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Thalia (Θαλία)', '希腊语', '丰饶、奢华与繁荣的生命', '当你处于丰盛、奢华且繁荣绽放的生命状态，享受富足时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ekstasis (ἔκστασις)', '希腊语', '出神状态', '当你处于自我之外的状态，如恍惚、出神或狂喜时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eunoia (εὔνοια)', '希腊语', '美好思维', '当你拥有美好或美丽的思想时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Víðsýni', '冰岛语', '全景视野与开放包容的心态', '当你拥有开阔的视野，以包容和开放的态度看待广阔世界时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Torschlusspanik', '德语', '错失机会的焦虑恐慌', '当你因生命机会减少而焦虑，或时间紧迫时匆忙行动。', 'https://hifisamurai.github.io/lexicography/'),
    -- peace/calm
    ('Xīn píng qì hé (心平氣和)', '中文', '心平气和', '当你心境平静、精神和谐时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Upekṣā/upekkhā (उपेक्षा)', '梵语', '平静与超然', '当你保持冷静、平衡并超然物外时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Xīn rú zhǐ shuǐ (心如止水)', '中文', '心如止水般的平静与安宁', '当你内心像静止的水面一样，与自己达成和解与平静时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Zanshin (残心)', '日语', '放松而警觉的心理状态', '当你面对压力或危险时，保持放松却高度警觉的心理状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eiréné (εἰρήνη)', '希腊语', '平静与安宁', '当你感到内心平和、完整且宁静休息时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Seijaku (静寂)', '日语', '喧嚣中的宁静与平和', '当你身处活动或混乱之中，依然保持内心的安静与平和时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Siga siga (σιγά σιγά)', '希腊语', '从容不迫', '当你缓慢、不慌不忙地行动时。', 'https://hifisamurai.github.io/lexicography/'),
    ('zìrán zìzài (自然自在)', '中文', '自然随性、自在无拘的状态', '当你展现出自然、随性、自在且无拘无束的优雅与轻松时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Otkhodchivyi (отходчивый)', '俄语', '豁达与不计较', '当你怒火平息后很快被安抚，或不记仇时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shalev (שָׁלֵו)', '希伯来语', '平静与安逸', '当你感到平静、安详、安静且自在时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kaif (кайф)', '俄语', '狂喜、满足与平静的感受', '当你体验到狂喜、高度满足感，同时伴随着内心的平静时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ayurnamat', '因纽特语', '斯多葛式的平静', '当你面对无法改变之事而不担忧时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Meriggiare', '意大利语', '午后小憩', '当你中午在阴凉处休息时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Otium', '拉丁语', '掌控时间的闲暇与安宁', '当你完全掌控自己的时间，享受闲暇、自由与安宁时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tarruru', '恩加卢马语', '傍晚的宁静', '当你看到暮色渐沉、心境平和安宁时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Leháro', '捷克语', '少责少劳的舒适闲适生活', '当你承担责任少、工作少，过着舒适且令人愉悦的闲适生活时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dwaal', '南非荷兰语', '梦幻般的恍惚状态', '当你处于梦幻、恍惚或心不在焉的状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sàn xīn (散心)', '中文', '排遣忧愁与放松身心的活动', '当你通过分散注意力来排遣忧愁、缓解无聊或放松身心时。', 'https://hifisamurai.github.io/lexicography/'),
    -- compassion/sympathy
    ('Omoiyari (思いやり)', '日语', '利他性的敏锐感知与体贴', '当你直觉理解他人的想法与感受，并据此采取行动时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Karuṇā (करुणा)', '梵语', '对他者苦难的共情与慈悲', '当你深切感知并认同他人的痛苦时，心中涌起的慈悲与共鸣。', 'https://hifisamurai.github.io/lexicography/'),
    ('Koev halev (כואב לי הלב)', '希伯来语', '对他者苦难的共情与慈悲', '当你深切感知并认同他人的痛苦时，心中涌起的慈悲与共鸣。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hésed/chésed/khésed (חֶ֫סֶד)', '希伯来语', '充满慈爱、忠诚与仁慈', '当你展现出对创造物的爱、忠诚与仁慈时，那种神圣的慈爱。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nachat (נחת)', '希伯来语', '欣慰与自豪', '当你为他人的成功感到骄傲和快乐时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Naches', '意第绪语', '欣慰与自豪', '当你为他人的成功感到骄傲和快乐时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Don de soi', '法语', '自我奉献与利他主义', '当你将自己奉献或牺牲给他人时，那种无私的行为与精神。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kreng-jai (เกรงใจ)', '泰语', '顾及他人感受的体贴之心', '当你优先考虑他人感受而不愿给对方增添负担时，那份体贴与尊重。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fargin', '意第绪语', '对他人的成功感到由衷自豪', '当你毫不吝啬地对他人的成功感到骄傲并表达喜悦时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Fremdschämen', '德语', '替人尴尬', '当你为他人的行为感到尴尬或羞愧时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gunnen', '荷兰语', '认为他人值得拥有并为其高兴', '当你认为某人值得获得美好事物，并为其得到而感到开心时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kvell', '意第绪语', '对他人的成功感到强烈自豪', '当你对他人的成就感到强烈且外显的骄傲与快乐时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Shù (恕)', '中文', '宽恕与仁慈的互惠', '在人际交往中，当你选择原谅他人的过错，以仁慈之心回应，并践行推己及人的原则时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Myötähäpeä', '芬兰语', '因他人出丑而产生的尴尬', '当你因他人的尴尬处境而感到局促不安时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pena ajena', '西班牙语', '因他人出丑而产生的尴尬', '当你因他人的尴尬处境而感到局促不安时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Anukampā (अनुकम्पा)', '梵语', '和谐共鸣与同情', '当你感受到与他人情感和谐共鸣时，那份同情与同理心。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pole', '斯瓦希里语', '表达歉意、同情与理解', '当你表达歉意，同时传达对他人的同情与理解时。', 'https://hifisamurai.github.io/lexicography/'),
    -- personality
    ('Qì zhì (氣质)', '中文', '独特迷人的个人气质', '当你展现出独特的性格品质、风度、魅力或吸引力，散发出一种迷人的磁石般的力量时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Lepos', '拉丁语', '魅力、优雅与机智', '当你感受到某人身上散发出的迷人风采、优雅举止与机智幽默时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Praotés (πρᾳότης)', '希腊语', '温和克制的善良品质', '当你表现出适度的力量与克制，有能力使用力量却选择克制，展现出温和、谦逊与善良时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yindyamarra', '澳大利亚原住民语', '尊重缓慢的谨慎态度', '当你表现出尊重，行动缓慢，小心行事，并在行动前仔细思考时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Seny', '加泰罗尼亚语', '务实明智的生活智慧', '当你拥有常识与智慧，做出务实且情绪稳定的明智判断，展现出洞察力、自觉与正直时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Salado', '西班牙语', '风趣幽默的可爱之人', '当你是一个讨人喜欢、善于交际的人，能敏锐地发现生活中的幽默并逗乐他人时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kokusaijin (国際人)', '日语', '国际化的人生态度', '当你具有世界主义视野，思维灵活且思想开放，能够适应不同文化背景时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mohamaatam', '泰卢固语', '顺从害羞的取悦意愿', '当你表现出顺从、犹豫、羞怯，并愿意取悦他人时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Luftmensch', '意第绪语', '脱离实际的空想家', '当你更关注智力或创造性追求，而非实际问题，成为一个只关心精神世界的空想家时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Laissez-faire', '法语', '顺其自然的放任态度', '当你倾向于让事物自行发展，不加以干涉，表现出一种顺其自然或愿意放任不管的态度时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    -- psychology
    ('Honne (本音)', '日语', '本音与真实情感', '当你表达内心真实的感受与愿望，而非对外展示的立场时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tatemae (建前)', '日语', '建前与表面立场', '当你为了社交场合而呈现出的表面意见或立场，与内心真实想法相对时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ego', '拉丁语', '自我与自我感', '当你意识到那个代表“我”的心理结构，并体验到对自我的整体感知与认同感时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Idée fixe', '法语', '执念与固定观念', '当你脑海中占据主导地位、难以摆脱甚至试图修改却无果的固定想法时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Stimmung', '德语', '情绪、氛围与和谐', '当你沉浸在某种特定的情绪、心境或周围弥漫的氛围中，感到事物相互交织时，便处于这种状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Superego', '拉丁语', '内化的社会道德监督', '当你内心将社会规范与价值观内化，形成高于自我的道德监督结构时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Unbewusste', '德语', '无法被意识察觉的心智', '当你意识到那些无法通过意识检查访问的心智层面时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Vedanā (वेदना)', '梵语', '感官对象的情感基调', '当你感知到感官对象带来的愉悦、不悦或中性的基本情感色调时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Freier Einfall', '德语', '自由自发的思想涌现', '当你经历自由、自发的思想涌现、联想或侵入时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mentalizar', '西班牙语', '进入思维框架与觉察', '当你进入某种思维框架，或使某事变得清晰可感、意识到内心状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Metaxy/u (μεταξύ)', '希腊语', '既分离又连接的中间地带', '当你处于两个领域或现实之间的中间地带，既分离又连接，参与不同层面时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nous (νοῦν)', '希腊语', '心智、理解与理性', '当你运用心智、理解力、理性或智力去认知世界时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Saṃskāra (संस्कार)', '梵语', '心理习气与业力印记', '当你体验到心理意志形成、业力印记或受条件制约的心理状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sī weí (思维)', '中文', '思维过程与视角', '当你经历思考的路径、心理过程或形成特定视角时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kopfkino', '德语', '脑海中的主观影像', '当你闭上眼睛，脑海中浮现出主观的内部图像或场景时，这是你心灵之眼所见的画面。', 'https://hifisamurai.github.io/lexicography/'),
    ('Utura-utura (うつらうつら)', '日语', '半梦半醒的恍惚状态', '当你处于睡眠与清醒之间摇摆不定的状态时，这是那种迷迷糊糊的感觉。', 'https://hifisamurai.github.io/lexicography/'),
    -- ambivalence
    ('Vague à l''âme', '法语', '灵魂深处的淡淡忧伤', '当你感到一种温柔、惆怅且略带忧郁的灵魂不适时，这种模糊的悲伤便笼罩着你。', 'https://hifisamurai.github.io/lexicography/'),
    ('Lè jí sheng bēi (樂極生悲)', '中文', '乐极生悲的必然转折', '当你经历极度的快乐后，悲伤不可避免地随之而来，这是快乐顶点引发悲伤的状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Chipe', '西班牙语', '因爱人分心而生的嫉妒', '当你感到爱人的注意力被他人占据时，这种嫉妒或竞争感便油然而生。', 'https://hifisamurai.github.io/lexicography/'),
    ('Desasosiego', '西班牙语', '身心不安的空虚渴望', '当你无法在身心找到安宁，感到空虚、不安、不适、渴望与欲望交织时，这种状态便存在。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wohlweh', '德语', '令人愉悦的疼痛体验', '当你按摩酸痛肌肉，体验到一种令人愉悦的疼痛时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Flygskam', '瑞典语', '因环保而羞愧', '当你因乘坐飞机对环境的负面影响而感到羞愧或尴尬时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Krasosmutněn', '捷克语', '美丽而快乐的悲伤', '当你体验到一种既美丽又带有快乐色彩的悲伤时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nadryv (надрыв)', '俄语', '压抑情感的失控爆发', '当你内心深处隐藏的情感被释放时，这种不受控制甚至非理性的情感爆发便发生了。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gedenkstätte', '德语', '纪念与反思之地', '当你身处纪念堂或纪念馆，进行缅怀、记忆与反思时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hamsterkäufe', '德语', '因恐慌而抢购囤积物资', '当你因恐慌而抢购并囤积生活物资时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Uffda, aka oofta, huffda', '挪威语', '惊讶疲惫交织的感叹', '当你感到惊讶、疲惫、沮丧或如释重负时，这种涵盖多种情绪的感叹词便脱口而出。', 'https://hifisamurai.github.io/lexicography/'),
    ('Lebenskrankheit', '德语', '存在性疏离与厌倦', '当你感到存在性疏离或对世界感到厌倦时。', 'https://hifisamurai.github.io/lexicography/'),
    -- freedom
    ('Wanderlust', '德语', '远足旅行的渴望', '当你渴望徒步旅行，对旅行和冒险怀有强烈向往时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Resfeber', '瑞典语', '出行前的兴奋', '当你即将踏上旅程，体验到兴奋与紧张交织的心情时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Waldeinsamkeit', '德语', '林间独处时的奇异孤独', '当你独自在树林中，感受到一种奇异或孤独的独处感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Dépayser', '法语', '身处异乡的陌生感', '当你身处异国他乡，体验到一种未必令人不快的陌生感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eleutheromania (ελευθερομανία)', '希腊语', '强烈且不可抑制的自由渴望', '当你怀有强烈且不可抑制的对自由的渴望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Prostor (простор)', '俄语', '空间广阔且无拘无束', '当你感受到空间的广阔、自由且无拘无束时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tîeow (เที่ยว)', '泰语', '无忧无虑的四处漫游', '当你无忧无虑地四处游荡或漫游时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Scatenarsi', '意大利语', '挣脱束缚的狂野', '当你彻底摆脱枷锁，肆意妄为、冲破常规束缚，体验极致自由与释放的瞬间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Eleuthería (ἐλευθερία)', '希腊语', '自由、解放与不受约束', '当你感受到自由、解放或不受约束的状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Schwellenangst', '德语', '跨越门槛的焦虑', '当你面对物理或隐喻意义上的门槛时，内心涌起的对跨越未知或界限的恐惧与不安。', 'https://hifisamurai.github.io/lexicography/'),
    ('Menefreghismo', '意大利语', '满不在乎的冷漠态度', '当你持有一种毫不在意、完全不在乎的态度时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kaaruwa', '豪萨语', '独立自由的离异女性', '当你作为离异或丧偶女性，保持独立与自由时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Viitsimine', '爱沙尼亚语', '不想做某事的抗拒', '当你内心强烈排斥某件事，产生不想去做、无法行动的心理抗拒状态。', 'https://hifisamurai.github.io/lexicography/'),
    -- kindness
    ('Utang na loob', '他加禄语', '无法偿还的感恩债务', '当你接受了一份巨大的恩惠或祝福，内心涌起一种无法用对等方式回报的深沉感激与亏欠感。', 'https://hifisamurai.github.io/lexicography/'),
    ('Nam jai (น้ำใจ)', '泰语', '源自心底的善意', '当你付出无私慷慨与善意，如水从心中流出般自然关怀他人时，感受到的温暖连接。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ubuntu', '祖鲁语/科萨语', '基于人性的善良', '当你因共同的人性而善待他人，在相互依存中体现善良与关怀时，感受到的深层连接。', 'https://hifisamurai.github.io/lexicography/'),
    ('Maitrī/mettā (मैत्री)', '梵语', '对众生的慈爱与友善', '当你心中充满对众生的慈爱与友善，传递温暖与善意时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Manaakitanga', '毛利语', '款待与尊重的关怀', '当你以好客、慷慨、支持和尊重对待他人，展现深切关怀与照顾时，感受到的互助精神。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pittiarniq', '因纽特语', '充满善意的关爱', '当你以善良和美好的态度对待他人，传递爱与关怀时，感受到的温暖与善意。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kokua', '夏威夷语', '无私互助的精神', '当你无私地提供帮助、援助或支持，与他人共同分担困难时，感受到的互助与关怀。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mazal tov (מזל טוב)', '希伯来语', '表达好运与幸福的美好祝愿', '当你庆祝喜事时，表达拥有好运、健康与幸福的美好祝愿，分享喜悦的时刻。', 'https://hifisamurai.github.io/lexicography/'),
    -- grit
    ('Sisu', '芬兰语', '逆境中的非凡决心', '当你身处逆境时，展现出超越常人的决心与勇气，坚持到底的精神力量。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ganbaru (頑張る)', '日语', '站稳脚跟并全力以赴', '当你面对挑战时，选择坚定立场并付出最大努力以做到最好。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ihuma', '因纽特语', '面对困境的冷静智慧', '当你面对困难和挫折时，保持冷静、乐观的耐心，并展现出尊重他人独立的现实与灵活。', 'https://hifisamurai.github.io/lexicography/'),
    ('Að nenna', '冰岛语', '坚持做事的意愿与能力', '当你面对艰难或枯燥的任务时，依然拥有愿意并能够坚持下去的心理状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hypomonē (ὑπομονή)', '希腊语', '恒常性与坚定的站立', '当你展现出恒常的耐力，在压力下坚定站立并坚持到底时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sumud (صمود)', '阿拉伯语', '坚定不移的持久抗争', '当你为了坚持某种信念或生存，展现出坚定且持续的抗争与执着时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Makrothumeó (μακροθυμέω)', '希腊语', '忍耐与不轻易动怒', '当你表现出极大的忍耐和宽恕，不易愤怒或寻求报复时，所体现的长期受苦的能力。', 'https://hifisamurai.github.io/lexicography/'),
    ('Sitzfleisch', '德语', '坚持完成枯燥任务的能力', '当你愿意或能够坚持完成那些艰难或枯燥的任务时，所体现出的持久力。', 'https://hifisamurai.github.io/lexicography/'),
    ('Engelengeduld', '荷兰语', '天使般的极大耐心', '当你面对繁琐或令人沮丧的情况时，展现出如天使般巨大且平和的耐心。', 'https://hifisamurai.github.io/lexicography/'),
    ('Inat', '塞尔维亚语', '骄傲的固执与自保', '当你出于骄傲和反抗心理，坚持自我保存时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Stehaufmännchen', '德语', '总能重新站起的韧性', '当你像不倒翁玩具一样，无论遭遇何种挫折总能重新振作并恢复原状时。', 'https://hifisamurai.github.io/lexicography/'),
    -- contentment
    ('Xìngfú (幸福)', '中文', '幸运的祝福与深层幸福', '当你感受到幸运与祝福交织，体验到深层的快乐与内心的满足与安宁时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Womba', '巴克韦里语', '熟睡孩子的微笑', '当你注视熟睡孩子脸上露出的安详微笑时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kǔ qù gān lái (苦去甘來)', '中文', '苦尽后的甘甜与解脱', '当你经历艰难时光后，迎来幸福或解脱的时刻。', 'https://hifisamurai.github.io/lexicography/'),
    ('Yuán man (圆满)', '中文', '完美与圆满的结局', '当你感到完美、令人满意、完全闭合或拥有幸福结局时', 'https://hifisamurai.github.io/lexicography/'),
    ('Xīn wèi (欣慰)', '中文', '欣慰与宽慰的喜悦', '当你感到快乐、宽慰、舒适、高兴或满足时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Elmosolyodni', '匈牙利语', '微妙的浅笑与萌芽', '当你脸上浮现出微妙的浅笑，即完整微笑的开端时', 'https://hifisamurai.github.io/lexicography/'),
    ('Osher (אושר)', '希伯来语', '喜悦与满足的幸福', '当你感受到内心充盈的喜悦与满足的幸福时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Rè ài (热爱)', '中文', '热烈而深情的热爱', '当你以非浪漫方式热烈激情地爱着某事或某人时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Labůžo', '捷克语', '享受与满足的境况', '当你处于有利情境，正享受或品味某事而感到满足时', 'https://hifisamurai.github.io/lexicography/'),
    ('Hyppytyynytyydytys', '芬兰语', '坐在舒适椅子上的放松', '当你坐在舒适的椅子上，感受到如充气垫般令人放松的满足感时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Veget', '捷克语', '闲适与安宁的休息', '当你处于无所事事、简朴生活且不受打扰的安宁休息状态时', 'https://hifisamurai.github.io/lexicography/'),
    -- hope/anticipation
    ('Vorfreude', '德语', '期待未来的喜悦', '当你因想象未来的快乐而产生强烈喜悦的期待时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Pàn tóu (盼头)', '中文', '对未来的确信希望与期待', '当你确信某事即将发生，心中充满对美好前景的期待与盼望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Iktsuarpok', '因纽特语', '等待某人时的急切期盼', '当你因等待某人归来而不断向外张望，心中充满期盼时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Þetta reddast', '冰岛语', '困境中依然相信会好转', '当事情看似不乐观，但你依然相信一切最终都会好起来时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Qarrtsiluni', '因纽特语', '黑暗中静待事件发生的时刻', '当你们在黑暗中静坐，怀着期待等待某事发生或爆发时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Avos (авось)', '俄语', '寄望好运的也许', '当你怀着对运气、机缘或命运的信任与希望说也许时', 'https://hifisamurai.github.io/lexicography/'),
    ('Belum', '印度尼西亚语', '尚未发生的希望愿望', '当你表达尚未发生、也许或充满希望的愿望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('In sha'' Allah (إِن شَاءَ اَللّٰه)', '阿拉伯语', '祈愿上帝所愿', '当你表达如上帝所愿般充满希望的愿望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Magari', '意大利语', '充满希望的遗憾愿望', '当你怀着希望、遗憾或梦幻般的愿望说也许时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ojalá', '西班牙语', '充满希望的祈愿', '当你表达如上帝所愿般充满希望的愿望时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wunschtraum', '德语', '美好却虚幻的梦想', '当你怀揣着宏大却难以实现的愿望，或沉浸在美好的幻想中时。', 'https://hifisamurai.github.io/lexicography/'),
    -- joy/bliss
    ('Iduni', '约鲁巴语', '强烈到无法言说的绝对喜悦', '喜悦强烈、完整又难以描述，仿佛普通语言已经无法容纳它。', 'https://hifisamurai.github.io/lexicography/'),
    ('Tarab (طرب)', '阿拉伯语', '音乐引发的陶醉与狂喜', '音乐让你完全沉浸，情绪被旋律推向陶醉、着迷甚至狂喜。', 'https://hifisamurai.github.io/lexicography/'),
    ('Freudentaumel', '德语', '因快乐而陶醉眩晕的状态', '当你因极度的快乐而感到陶醉、欣喜若狂甚至眩晕时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Bazodee', '克里奥尔语', '令人陶醉的困惑与快乐', '当你感到快乐得晕头转向，处于一种陶醉的困惑状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Béatitude', '法语', '至福与神圣的幸福状态', '当你处于极致的幸福之中，感受到一种神圣的福佑状态时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Saṃtoṣa/santosa (संतोष)', '梵语', '完全知足与满足的状态', '当你感到内心完全知足，对现状感到满意与满足时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Suaimhneas croí', '爱尔兰语', '完成任务后的平静与满足', '当你完成某项任务后，内心感到幸福、平静与放松时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gaudere', '拉丁语', '享受欢乐与喜悦', '当你沉浸在欢乐之中，从某事中感受到喜悦时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jouissance', '法语', '身心愉悦或狂喜的状态', '当你感受到身体或智力上的极大愉悦、快乐或狂喜时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Mechaye', '意第绪语', '带来极大喜悦的事物', '当你感受到巨大的快乐，或遇到带来极大喜悦的事物时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Charis (χαρις)', '希腊语', '优雅仁慈的高贵之美', '当你感受到优雅、仁慈、美丽或高贵的品质时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Herrliche Gefühle', '德语', '赋予生命的美好情感', '当你体验到那些被描述为赋予生命的美好情感与感受时。', 'https://hifisamurai.github.io/lexicography/'),
    -- affection
    ('Gigil', '他加禄语', '因喜爱而忍不住想捏人的冲动', '某个人可爱得让你产生难以抵挡的冲动，想轻轻捏一捏或抱紧对方。', 'https://hifisamurai.github.io/lexicography/'),
    ('Gemas', '印度尼西亚语', '因觉得可爱而想抱紧对方', '爱意和可爱感同时涌来，让你很想拥抱、轻捏或挤一挤对方。', 'https://hifisamurai.github.io/lexicography/'),
    ('Innig', '德语', '发自内心的温柔、忠诚与亲密', '你对一个人怀有真挚而温柔的感情，其中包含投入、亲密与珍视。', 'https://hifisamurai.github.io/lexicography/'),
    ('Uňuhňat', '捷克语', '用拥抱或爱抚表达无尽的爱', '当你想要通过拥抱或爱抚来给予某人无尽的爱意时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Frimousse', '法语', '令人心生喜爱的可爱脸庞', '看到一张甜美可爱的小脸时，你自然感到亲近，也忍不住多看一眼。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kanyi(r)ninpa', '平图皮语', '亲密照护者与被照护者的关系', '当你处于一种亲密且积极的照护关系中，体现紧密联结。', 'https://hifisamurai.github.io/lexicography/'),
    ('Colo', '葡萄牙语', '双臂与胸口围成的怀抱', '你用胸口和双臂把一个人拥进怀里，形成可以依靠和被承接的空间。', 'https://hifisamurai.github.io/lexicography/'),
    ('Famn', '瑞典语', '双臂之间可以拥抱人的空间', '一个人被揽进双臂之间，那片怀抱既是身体空间，也传递亲近。', 'https://hifisamurai.github.io/lexicography/'),
    ('Aradupopini', '图卢语', '挽臂或牵手并肩行走', '你和另一个人挽着手臂或牵着手向前走，亲密存在于并肩的动作里。', 'https://hifisamurai.github.io/lexicography/'),
    ('Vískat', '捷克语', '用手轻轻拨弄对方的头发', '你熟悉而自然地拨弄一个人的头发，这个小动作带着亲昵意味。', 'https://hifisamurai.github.io/lexicography/'),
    -- pleasure
    ('Guò yǐn (過癮)', '中文', '得到充分满足的畅快享受', '某次体验带来强烈而充分的愉悦，让你觉得尽兴、满足又痛快。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kāi xīn (开心)', '中文', '打开心扉的短暂快乐', '当你打开心扉，这种相对短暂或瞬间的快乐让你感到轻松与愉悦。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kuài lè (快乐)', '中文', '快速而持续的愉悦快乐', '当你感到快乐与满足，这种即时的愉悦构成了你生活中的幸福时刻。', 'https://hifisamurai.github.io/lexicography/'),
    ('Deliciate', '英语', '沉溺于强烈的愉悦之中', '当你沉溺于强烈的愉悦，这种纵情享受的感觉让你沉浸在极致的快乐里。', 'https://hifisamurai.github.io/lexicography/'),
    ('Lekker', '荷兰语', '兼具美味、舒适与愉悦的感受', '食物很好吃，或环境让人放松舒服时，你感到直接而鲜明的愉快。', 'https://hifisamurai.github.io/lexicography/'),
    ('Arbejdsglaede', '丹麦语', '从工作中获得的愉悦与满足', '当你从劳动中获得快乐与满足，内心感到充实时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Binnenpretje', '荷兰语', '私密的内部玩笑或乐趣', '当你独自享受一个秘密笑话或内部乐趣时，这种私密的愉悦只属于你。', 'https://hifisamurai.github.io/lexicography/'),
    ('Ingiogatzau', '撒丁语', '在玩笑与嬉戏中涌出的快乐', '你用开玩笑和嬉戏的方式分享快乐，气氛轻松而充满活力。', 'https://hifisamurai.github.io/lexicography/'),
    -- desire
    ('Mamihlapinatapai', '亚甘语', '无声却相互渴望的眼神', '当你们对视，这种无声却相互渴望的眼神传达了彼此未说出口的情意。', 'https://hifisamurai.github.io/lexicography/'),
    ('Jī qíng (激情)', '中文', '浪漫或性方面的激情', '当你感受到浪漫或性方面的激情，这种炽热的情感充满了你的内心。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kapsoura (Καψούρα)', '希腊语', '迷恋或热恋初期的激情', '当你处于迷恋或热恋初期，这种强烈的浪漫激情让你感到头晕目眩。', 'https://hifisamurai.github.io/lexicography/'),
    ('Neprieinamas', '立陶宛语', '难以诱惑或打动的人', '当你面对一个极难被诱惑或打动的人，这种不可触及感让你感到无奈。', 'https://hifisamurai.github.io/lexicography/'),
    -- friendship
    ('Nakama (仲間)', '日语', '挚友或亲密伙伴', '当你与某人拥有深厚的柏拉图式情感，视其为亲密伙伴时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Lǎo tóng (老同)', '中文', '终身挚友或知己', '当你与另一人建立起永恒且深厚的知己情谊时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Amae (甘え)', '日语', '含蓄地请求关爱或纵容', '当你以被动姿态隐含地请求对方满足你的需求或给予宠爱时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Philotimo (φιλότιμο)', '希腊语', '对荣誉的热爱与尊重', '当你重视并尊重亲友，体现对关系的珍视时。', 'https://hifisamurai.github.io/lexicography/'),
    -- excitement/intensity
    ('Hết sảy', '越南语', '兴奋到难以用语言形容', '一段体验精彩得超出预期，兴奋和赞叹强烈到几乎说不出话。', 'https://hifisamurai.github.io/lexicography/'),
    ('Frisson', '法语', '恐惧与兴奋交织的战栗', '突如其来的刺激掠过身体，害怕与兴奋同时化成一阵战栗。', 'https://hifisamurai.github.io/lexicography/'),
    ('Herzklopfen', '德语', '期待之中加速的心跳', '等待好事或坏事发生时，强烈期待让心脏一下下重重跳动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Schwärmerei', '德语', '过度强烈的狂热或感伤', '热情或感伤上升到难以控制的程度，几乎占据了整个心绪。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hwyl', '威尔士语', '充满情感动力的热烈兴致', '情绪、旋律感与动力一起升高，你感到热烈、振奋并受到鼓舞。', 'https://hifisamurai.github.io/lexicography/'),
    ('Azart (азарт)', '俄语', '热情、兴奋或狂热', '当你充满热情地做某事，或表现出狂热、甚至鲁莽冒险的态度时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Capoter', '法语', '欣喜若狂或不知所措', '当你因极度喜悦而兴奋，或因压力过大而感到不知所措时。', 'https://hifisamurai.github.io/lexicography/'),
    -- awareness
    ('Kokoro (心)', '日语', '心、思想与精神的统一', '身体感受、思想和精神不再彼此分开，而像一个完整的内在整体。', 'https://hifisamurai.github.io/lexicography/'),
    ('Xīn (心)', '中文', '身心与精神的统一', '当你将心脏、心智甚至精神合而为一进行体验时，便是 Xīn 的核心含义。', 'https://hifisamurai.github.io/lexicography/'),
    ('Samādhi (समाधि)', '梵语', '高度专注而整合统一的心境', '注意力集中到一点，内心逐渐呈现整合、统一和完整的状态。', 'https://hifisamurai.github.io/lexicography/'),
    ('Wú xin (無心)', '中文', '不被念头与情绪占据的空明', '心不再黏附外界刺激，也没有被固定的思想或情绪牢牢占据。', 'https://hifisamurai.github.io/lexicography/'),
    ('Smṛti / sati (स्मृति)', '梵语', '对当下保持清楚的忆念与觉知', '你把注意力放在正在发生的此刻，持续记得观察自己的经验。', 'https://hifisamurai.github.io/lexicography/'),
    ('Citta (चित्त)', '梵语', '心智、意识与觉知', '你关注内在正在思考、感受和觉察的部分，试图看清心的活动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Samprajanya (संप्रज़न्ऩा)', '梵语', '清晰觉知与正念', '当你保持清晰理解力，并带着精神进步感的正念时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Śamatha/samatha (शमथ)', '梵语', '平静与专注冥想', '当你通过止息、放缓或专注冥想使内心平静时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Kekau', '印度尼西亚语', '惊醒与回归现实', '当你从睡眠中突然惊醒，或在噩梦后恢复意识并回归现实时。', 'https://hifisamurai.github.io/lexicography/'),
    -- cosiness/homeliness
    ('Gemütlichkeit', '德语', '舒适、亲切而像家一样的氛围', '环境让你感到舒服、亲切和熟悉，仿佛可以放心待在家中。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hyggelig', '丹麦语', '温暖、友好而舒适的愉快', '人与环境都显得温暖友好，你在其中感到轻松、舒服和愉快。', 'https://hifisamurai.github.io/lexicography/'),
    ('Hyggekrog', '丹麦语', '房间里最舒适安心的小角落', '你在房间里找到一个温暖安静的角落，可以蜷缩、休息并放松下来。', 'https://hifisamurai.github.io/lexicography/'),
    ('Peiskos', '挪威语', '壁炉前被火光包围的暖意', '你坐在噼啪作响的壁炉前，让火光和温度带来安稳惬意。', 'https://hifisamurai.github.io/lexicography/'),
    ('Focolare', '意大利语', '家庭情感中心', '当你身处壁炉旁，感受其作为家庭物理或情感中心时。', 'https://hifisamurai.github.io/lexicography/'),
    ('Heimlich', '德语', '私密熟悉或隐秘', '当你体验与家相关、舒适熟悉，或处于秘密隐秘状态时。', 'https://hifisamurai.github.io/lexicography/'),
    -- longing
    ('Saudosista', '葡萄牙语', '总被怀旧之情牵动的人', '你很容易沉入怀旧，常常被过去的人、地方或生活方式牵动。', 'https://hifisamurai.github.io/lexicography/'),
    ('Cocagne', '法语', '富足安逸的梦幻之地', '你想象一个不用辛劳、充满舒适与丰盛的地方，并渴望暂时住进那里。', 'https://hifisamurai.github.io/lexicography/')
ON CONFLICT (name, language) DO UPDATE SET
    meaning = EXCLUDED.meaning,
    description = EXCLUDED.description,
    source_url = EXCLUDED.source_url;
